# Observability keys received from Infra team.
cloud_id: "{{ elastic_cloud_id }}"
elastic_api_key: "{{ elastic_api_key }}"
grafana_cloud_api_key: "{{ grafana_cloud_api_key }}"

create_flamegraph: false
flamegraph_node_id: "0" # Validator node ID to generate flamegraph for

s3_bucket: "{{ releases_bucket }}"

snarkos_verbosity: "1"
rest_rps: 1000000000
