- name: Wait for SSH to become available
  hosts: all
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - name: Wait for SSH to become ready
      wait_for_connection:

- name: Set up and start snarkOS network for validators
  hosts: snarkos_node
  become: true
  vars_files:
    - vars.yml
  remote_user: ubuntu
  pre_tasks:
    - name: Gather facts from all nodes
      setup:

    - name: Determine the number of instances
      set_fact:
        num_instances: "{{ groups['snarkos_node'] | length }}"
      run_once: true

    - name: Collect and format validator IPs
      set_fact:
        formatted_validator_ips: "{{ groups['snarkos_node'] | map('extract', hostvars, ['public_ip_address']) | map('regex_replace', '^(.*)$', '\\1:5000') | join(',') }}"
      run_once: true

    - name: Set node_id based on instance tag
      set_fact:
        node_id: "{{ tags['Dev'] }}"

    - name: Set snarkos command with peers and validators
      set_fact:
        snarkos_command: "snarkos1 start --metrics --nodisplay --bft 0.0.0.0:5000 --rest 0.0.0.0:3030 --validators {{ formatted_validator_ips }} --verbosity 1 --dev {{ node_id }} --dev-num-validators {{ num_instances }} --validator --rest-rps 90000000 --no-dev-txs"
    - name: Debug snarkos command
      debug:
        msg: "The snarkos command for this client is: {{ snarkos_command }}"

    - name: Set snarkos command with peers and validators
      set_fact:
        snarkos_command_restricted: "snarkos2 start --metrics --nodisplay --bft 0.0.0.0:5000 --rest 0.0.0.0:3030 --validators {{ formatted_validator_ips }} --verbosity 1 --dev {{ node_id }} --dev-num-validators {{ num_instances }} --validator --rest-rps 90000000 --no-dev-txs"
    - name: Debug snarkos command
      debug:
        msg: "The snarkos command for this client is: {{ snarkos_command_restricted }}"

    - name: Download snarkOS binary with GitHub CLI # noqa: no-changed-when
      shell: >
        GITHUB_TOKEN="{{ github_token }}" gh release download v0-mainnet-staging
        --repo ProvableHQ/snarkOS-staging
        --pattern "snarkos*unknown-linux-gnu.zip"
        --output "/usr/bin/snarkos.zip"
        --clobber

        unzip -o /usr/bin/snarkos.zip -d /usr/bin

        mv /usr/bin/snarkos /usr/bin/snarkos1
      args:
        executable: /bin/bash
      become: true


    - name: Download snarkOS binary with GitHub CLI # noqa: no-changed-when
      shell: >
        GITHUB_TOKEN="{{ github_token }}" gh release download v0-mainnet-staging-restrictions
        --repo ProvableHQ/snarkOS-staging
        --pattern "snarkos*unknown-linux-gnu.zip"
        --output "/usr/bin/snarkos.zip"
        --clobber

        unzip -o /usr/bin/snarkos.zip -d /usr/bin

        mv /usr/bin/snarkos /usr/bin/snarkos2
      args:
        executable: /bin/bash
      become: true

    - name: Make snarkos1 executable
      file:
        path: /usr/bin/snarkos1
        mode: "0755"

    - name: Make snarkos2 executable
      file:
        path: /usr/bin/snarkos2
        mode: "0755"

    - name: Deploy the snarkos systemd service file
      template:
        src: snarkos.service
        dest: /etc/systemd/system/snarkos.service
        mode: '0644'
      become: true

    - name: Deploy the snarkos-restricted systemd service file
      template:
        src: snarkos-restricted.service
        dest: /etc/systemd/system/snarkos-restricted.service
        mode: '0644'
      become: true

    - name: Reload systemd to read new snarkos service files
      systemd:
        daemon_reload: true
      become: true

  tags: snarkos

# ------------------------------------------------
# snarkOS Process Exporter

- name: Install and Configure Process Exporter
  hosts: snarkos_node
  become: true
  remote_user: ubuntu
  roles:
    - process_exporter_setup
  tags: process_exporter

# ------------------------------------------------
# Logstash

- name: Install and Configure Logstash
  hosts: snarkos_node
  become: true
  vars_files:
    - vars.yml
  remote_user: ubuntu
  pre_tasks:
    - name: Slurp the commit hash
      ansible.builtin.slurp:
        src: /usr/bin/SNARKOS_COMMIT_HASH
      register: file_content_encoded

    - name: Decode the file commit from base64
      set_fact:
        commit_hash: "{{ file_content_encoded['content'] | b64decode | trim }}"

    - name: Set host_public_ip
      set_fact:
        host_public_ip: "{{ hostvars[inventory_hostname]['public_ip_address'] }}"

    - name: Set node_id based on instance tag
      set_fact:
        node_id: "{{ tags['Dev'] }}"
  roles:
    - logstash_setup
  tags: logstash

# ------------------------------------------------
# Prometheus for Grafana metrics

- name: Install and Configure Prometheus
  hosts: prometheus_server
  become: true
  vars_files:
    - vars.yml
  remote_user: ubuntu
  gather_facts: true
  roles:
    - prometheus_setup
  tags: prometheus

