# ------------------------------------------------
# tx-cannon

# Get load balancer DNS name
- name: Gather information about all ELBs
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get info about all classic ELBs
      community.aws.elb_classic_lb_info:
        names: snarkos-lb
        region: us-west-1
      register: elb_info

    - name: Set DNS name as a fact
      set_fact:
        snarkos_lb_dns: "{{ elb_info.elbs[0].dns_name }}"

    - ansible.builtin.debug:
        msg: "The DNS name of snarkos-lb is {{ snarkos_lb_dns }}"

    - name: Wait for the network to be healthy
      uri:
        url: "http://{{ snarkos_lb_dns }}:3030/mainnet/latest/height"
        method: GET
        status_code: 200
        timeout: 10
      register: result
      until: result.status == 200
      retries: 10
      delay: 10
  tags: tx-cannon

- name: Ensure block height is at least 10 before proceeding with restart test
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch the current block from the load balancer
      uri:
        url: "http://{{ snarkos_lb_dns }}:3030/mainnet/block/latest"
        method: GET
        return_content: true
      register: lb_current_block
      until: (lb_current_block.json['header']['metadata']['height'] | int) >= 10
      retries: 30
      delay: 10
      ignore_errors: yes

    - name: Print LB current block height
      debug:
        msg: "LB Current Block height is now {{ lb_current_block.json['header']['metadata']['height'] }}"

- name: BFT-Swap - Cycle each validator set three times
  hosts: localhost
  gather_facts: no
  vars:
    num_cycles: 3
  tasks:
    - name: Initialize cycle counter
      set_fact:
        cycle_counter: 0

    - name: Cycle through swap process for each cycle
      include_tasks: swap_cycle.yml
      loop: "{{ range(0, num_cycles) | list }}"
      loop_control:
        loop_var: cycle_index
      vars:
        batched_groups: "{{ groups['snarkos_node'] | batch(3) | list }}"
        current_group: "{{ batched_groups[cycle_index | int % batched_groups | length] }}"
        source_node: "{{ groups['snarkos_node'] | difference(current_group) | first }}"

    - name: Increment cycle counter
      set_fact:
        cycle_counter: "{{ cycle_counter | int + 1 }}"
