# snarkos_setup.yml
- name: Wait for SSH to become available
  hosts: "snarkos_node"
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - name: Wait for SSH to become ready
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        timeout: 300
        delay: 10
        state: started

- name: Set up snarkOS nodes
  hosts: "snarkos_node"
  become: yes
  remote_user: ubuntu
  vars:
    branch: "mainnet_no_tx_generation"
    verbosity: "4"
  tasks:
    - name: Gather facts from all nodes
      setup:

    - name: Set first node IP address
      set_fact:
        first_node_ip: "{{ hostvars[groups['snarkos_node'][0]]['public_ip_address']}}"
      when: groups['snarkos_node'] is defined and groups['snarkos_node'] | length > 0
      run_once: true

    - name: Determine the number of instances
      set_fact:
        num_instances: "{{ groups['snarkos_node'] | length }}"
      run_once: true

    - name: Set node_id based on instance tag
      set_fact:
        node_id: "{{ tags['Dev'] }}"
      loop: "{{ groups['snarkos_node'] }}"
      run_once: true
      loop_control:
        loop_var: instance

    - name: Install SnarkOS binaries
      shell: |
        curl -L https://github.com/iamalwaysuncomfortable/snarkOS/releases/download/v2.2.8-latest/snarkos-v2.2.8-latest-x86_64-unknown-linux-gnu.zip -o snarkos.zip
        sudo apt-get install unzip
        sudo unzip -o snarkos.zip -d /usr/bin
      args:
        executable: /bin/bash
      become: yes

    - name: Make snarkos executable
      file:
        path: "/usr/bin/snarkos"
        mode: '0755'

    - name: Set environment variables for snarkos service
      set_fact:
        ansible_env:
          FIRST_NODE_IP: "{{ first_node_ip }}"
          VERBOSITY: "{{ verbosity }}"
          NODE_ID: "{{ node_id }}"
          NUM_INSTANCES: "{{ num_instances }}"
      tags: always

    - name: Deploy the snarkos systemd service file
      template:
        src: snarkos.service
        dest: /etc/systemd/system/snarkos.service
      become: yes

    - name: Reload systemd to read new snarkos service file
      systemd:
        daemon_reload: yes
      become: yes

    - name: Restart snarkos service
      systemd:
        name: snarkos
        state: restarted
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started

    - name: Run Docker Process Exporter for snarkos
      ansible.builtin.shell: >
        docker run -d --rm -p 9256:9256 --privileged -v /proc:/host/proc -v $(pwd):/config ncabatoff/process-exporter --procfs /host/proc -procnames snarkos
      args:
        executable: /bin/bash

# logstash
- name: Install and Configure Logstash
  hosts: "snarkos_node"
  become: yes
  remote_user: ubuntu

  vars:
    cloud_id: "{{ lookup('env', 'ELASTIC_CLOUD_ID') }}"
    api_key: "{{ lookup('env', 'ELASTIC_API_KEY') }}"
    devnet_name: "{{ lookup('env', 'DEVNET_NAME') }}"

  tasks:
    - name: Set AWS Region Fact
      set_fact:
        aws_region: "{{ ansible_host.split('.')[1] }}"
      when: ansible_host is defined

    - name: Add Elastic GPG key
      ansible.builtin.shell:
        cmd: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --batch --yes --dearmor -o /usr/share/keyrings/elastic-keyring.gpg"

    - name: Add Elastic APT repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/elastic-8.x.list
        line: "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        create: yes
        state: present

    - name: Update and install Logstash
      ansible.builtin.apt:
        update_cache: yes
        name: logstash
        state: latest

    - name: Copy Logstash Configuration Template
      ansible.builtin.template:
        src: logstash.conf
        dest: /etc/logstash/conf.d/logstash.conf
      vars:
        host_public_ip: "{{ hostvars[inventory_hostname]['public_ip_address'] }}" 

    - name: Start Logstash Service
      ansible.builtin.systemd:
        name: logstash
        state: started
        enabled: yes

# metrics on grafana
- name: Install prometheus and enable remote forwarding to Grafana cloud
  hosts: prometheus_server
  become: yes
  gather_facts: true
  vars:
    ansible_user: ubuntu
    grafana_cloud_api_key: "{{ lookup('env', 'GRAFANA_CLOUD_API_KEY') }}"
    devnet_name: "{{ lookup('env', 'DEVNET_NAME') }}"

  tasks:
    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
      become_user: ubuntu

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: "/usr/local/bin/docker-compose"
        mode: 'u+x,g+x'

    - name: Create YAML scrape target file of all nodes
      ansible.builtin.template:
        src: prometheus.yml
        dest: /home/ubuntu/prometheus.yml

    - name: Install unzip
      ansible.builtin.package:
        name: unzip
        state: present

    - name: Download, unzip, and set execute permissions on Grafana Agent
      ansible.builtin.shell: |
        curl -O -L "https://github.com/grafana/agent/releases/latest/download/grafana-agent-linux-amd64.zip" &&
        unzip "grafana-agent-linux-amd64.zip" &&
        chmod a+x grafana-agent-linux-amd64
      args:
        chdir: /home/ubuntu
        creates: grafana-agent-linux-amd64

    - name: Run docker-compose up
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/

# Setting up and running tx-cannon on tx-cannon instances
- name: Set up and run tx-cannon
  hosts: "tx_cannon_node"
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Clone or update tx-cannon
      git:
        repo: "https://{{ lookup('env', 'GITHUB_TOKEN') }}:x-oauth-basic@github.com/AleoHQ/tx-cannon.git"
        dest: "/home/ubuntu/tx-cannon"
        version: "mainnet"

    - name: Install the tx-cannon
      shell: |
        sudo apt-get install -y unzip
        sudo apt-get install -y jq
        RELEASE_DATA=$(curl -L https://$GITHUB_TOKEN:@api.github.com/repos/AleoHQ/tx-cannon/releases/latest)
        ASSET_ID=$(echo "${RELEASE_DATA}" | jq -r '.assets[] | select(.name == "tx-cannon-v0.1.0-x86_64-unknown-linux-gnu.zip") | .id')
        sudo curl -L -H 'Accept: application/octet-stream' https://$GITHUB_TOKEN:@api.github.com/repos/AleoHQ/tx-cannon/releases/assets/$ASSET_ID -o tx-cannon.zip
        sudo unzip -o tx-cannon.zip -d /usr/bin
      args:
        executable: /bin/bash
      become: yes
      environment:
        GITHUB_TOKEN: "{{ lookup('env', 'GITHUB_TOKEN') }}"

    - name: Make tx-cannon executable
      file:
        path: "/usr/bin/tx-cannon"
        mode: '0755'

    - name: Run tx-cannon network driver
      shell: |
        cd /home/ubuntu/tx-cannon
        sudo bash -c '/usr/bin/tx-cannon batch-execute --test tests/network_driver/network_driver.toml -e http://{{ test_network_url }}:3030 -r 9000001  >> tx-cannon.log 2>&1'
      args:
        executable: /bin/bash
      async: 36000  # Adjust based on expected duration of the tx-cannon run
      poll: 0

    - name: Deploy all necessary programs
      shell: |
        sleep 15 # Wait for the network driver to start
        sudo /bin/bash /home/ubuntu/tx-cannon/tests/ridiculous_finalize_hash/deploy.sh -c /usr/bin/tx-cannon -e http://{{ test_network_url }}:3030
      args:
        executable: /bin/bash
      run_once: true
      delegate_to: "{{ groups['tx_cannon_node'][0] }}"

    - name: Wait for the deployed program to be ready
      uri:
        url: "http://{{ test_network_url }}:3030/mainnet/program/large_bhp_256_50000.aleo"
        method: GET
        status_code: 200
        timeout: 10
      register: result
      until: result.status == 200
      retries: 60  # Number of retries
      delay: 10  # Delay in seconds between retries

    - name: Continue with tx-cannon batch-execute
      shell: |
        cd /home/ubuntu/tx-cannon
        sudo bash -c "/usr/bin/tx-cannon batch-execute --test tests/ridiculous_finalize_hash/bhp_hash_ramp_up.toml -e http://{{ test_network_url }}:3030  >> tx-cannon.log 2>&1"
      args:
        executable: /bin/bash
      async: 36000  # Adjust based on expected duration of the tx-cannon run
      poll: 0
