repos:
  - repo: local
    hooks:
      - id: ansible-lint
        name: Ansible Lint
        entry: ./lint.sh
        language: script
        pass_filenames: false
        always_run: true

      - id: shellcheck
        name: ShellCheck
        entry: bash -c 'find test_suites/snarkos-p2p-tests -name "*.sh" -print0 | xargs -0 shellcheck -x --source-path=SCRIPTDIR'
        language: system
        pass_filenames: false
        always_run: true
