# logstash_setup.yml
- name: Install and Configure Logstash
  hosts: "snarkos_node"
  become: yes
  remote_user: ubuntu

  vars_prompt:
    - name: cloud_id
      prompt: "Enter your Elastic Cloud ID"
      private: no
    - name: api_key
      prompt: "Enter your Elastic API Key"
      private: no

  tasks:
    - name: Set AWS Region Fact
      set_fact:
        aws_region: "{{ ansible_host.split('.')[1] }}"
      when: ansible_host is defined

    - name: Add Elastic GPG key
      ansible.builtin.shell:
        cmd: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --batch --yes --dearmor -o /usr/share/keyrings/elastic-keyring.gpg"

    - name: Add Elastic APT repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/elastic-8.x.list
        line: "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        create: yes
        state: present

    - name: Update and install Logstash
      ansible.builtin.apt:
        update_cache: yes
        name: logstash
        state: latest

    - name: Copy Logstash Configuration Template
      ansible.builtin.template:
        src: logstash.conf
        dest: /etc/logstash/conf.d/logstash.conf

    - name: Start Logstash Service
      ansible.builtin.systemd:
        name: logstash
        state: started
        enabled: yes
