- name: Print ips
  hosts: localhost
  tasks:
    - name: Print groups var
      debug:
        var: groups
    - name: Store client IPs
      copy:
        content: "{{ groups.get('snarkos_client', []) | map('extract', hostvars) | map(attribute='public_ip_address') | join('\n') }}"
        dest: ../client_ip_addresses.txt
    - name: Store validator IPs
      copy:
        content: "{{ groups.get('snarkos_validator', []) | map('extract', hostvars) | map(attribute='public_ip_address') | join('\n') }}"
        dest: ../ip_addresses.txt
