- name: check heights
  block:
  - name: Initialize attempt number if undefined
    set_fact:
      attempt_number: 0
    when: attempt_number is undefined

  - name: Initialize max attempts if undefined
    set_fact:
      max_attempts: 20
    when: max_attempts is undefined

  - name: wait 30 seconds
    pause:
      seconds: 30

  - name: Fetch the block from the node
    remote_user: ubuntu
    uri:
      url: "http://{{ node_to_check }}:3030/{{ snarkos_network }}/block/latest"
      method: GET
      return_content: true
    register: node_current_block
    retries: 5 
    delay: 2 
    until: node_current_block.status == 200

  - name: Fetch the block from the node to compare
    remote_user: ubuntu
    uri:
      url: "http://{{ node_to_compare }}:3030/{{ snarkos_network }}/block/latest"
      method: GET
      return_content: true
    register: node_current_block_compare
    retries: 10
    delay: 5
    until: node_current_block_compare.status == 200

  - name: Calculate height difference
    set_fact:
      height_difference: "{{ (node_current_block_compare.json['header']['metadata']['height'] | int) - (node_current_block.json['header']['metadata']['height'] | int) }}"

  - name: Verify height difference is within acceptable range
    fail:
      msg: "Height difference of {{ height_difference }} is not within the acceptable range."
    when: height_difference | int > 5 or height_difference | int < -5

  - name: Set sync successful
    set_fact:
      sync_successful: true
    when:
      - height_difference | int <= 5
      - height_difference | int >= -5

  rescue:
    - name: Retry message
      debug:
        msg: "Attempt {{ attempt_number | default(0) }} failed.  Previous node height: {{ node_current_block_compare.json['header']['metadata']['height'] }}, Current node height: {{ node_current_block.json['header']['metadata']['height'] }}. Retrying..."

    - name: print attempt number 
      debug:
        msg: "Attempt number: {{ attempt_number }}"

    - name: Increment attempt number
      set_fact:
        incremented_attempt_number: "{{ attempt_number | int + 1 }}"

    - name: Retry 
      include_tasks: is_synced.yml
      vars:
        attempt_number: "{{ incremented_attempt_number }}"
      when: attempt_number | int < max_attempts
