- name: Gather facts from all validators
  setup:

- name: Set global facts
  set_fact:
    num_instances: "{{ groups['snarkos_validator'] | length }}"
    malicemode: ""
  run_once: true

- name: Set instance-specific facts
  set_fact:
    formatted_validator_ips: >-
      {{
        groups['snarkos_validator']
        | map('extract', hostvars, ['public_ip_address'])
        | map('regex_replace', '^(.*)$', '\1:5000')
        | join(',')
      }}
    formatted_validator_routers: >-
      {{
        groups['snarkos_validator']
        | map('extract', hostvars, ['public_ip_address'])
        | map('regex_replace', '^(.*)$', '\1:4130')
        | join(',')
      }}
    node_id: "{{ tags['Dev'] }}"

- name: Collect client IPs for the current validator
  set_fact:
    peers_arg: >-
      {{ (
        groups.get('snarkos_prover', [])
          | map('extract', hostvars)
          | map(attribute='public_ip_address')
          | map('regex_replace', '^(.*)$', '\1:4130')
          | list
        )
        | join(',')
      }}

# The 34.12.32.12:9 ip is set to peers, because this is a workaround so that
# the node doesn't attempt to connect to itself as a peer,
# as 127.0.0.1 is the default dev peer right now if there are no --peers.
- name: Set snarkos command with peers and validators
  set_fact:
    snarkos_command: >-
      snarkos start --metrics --nodisplay  --validator \
        --node 0.0.0.0:4130  --bft 0.0.0.0:5000 --rest 0.0.0.0:3030 \
        --validators {{ formatted_validator_ips }} \
        --verbosity {{ snarkos_verbosity }} \
        --dev {{ node_id }} \
        --dev-num-validators {{ num_instances }} --no-dev-txs \
        --rest-rps {{ rest_rps }} \
        --allow-external-peers \
        --peers 34.12.32.12:9 \
        --network {{ snarkos_network_int }}

- name: Select global bootstrap clients (hostnames)
  set_fact:
    bootstrap_client_ips: "{{ hostvars['localhost'].bootstrap_client_ips }}"

- name: Build bootstrap_peers_arg with port suffix
  set_fact:
    bootstrap_peers_arg: "{{ bootstrap_client_ips | map('regex_replace', '^(.*)$', '\\1:4130') | join(',') }}"

- name: Build extra environment map for the validator service
  set_fact:
    snarkos_env_extra: >-
      {{
        {'TEST_BOOTSTRAP_PEERS': bootstrap_peers_arg}
      }}
