- name: Gather facts from all nodes
  setup:

- name: Determine the number of validators
  set_fact:
    num_instances: "{{ groups['snarkos_validator'] | length }}"
  run_once: true

- name: Assign client to validator index
  set_fact:
    validator_id: "{{ tags['Validator'] }}"

- name: Debug validator IP by Dev tag
  debug:
    msg: >-
      {{
        groups['snarkos_validator']
        | map('extract', hostvars)
        | selectattr('tags.Dev', 'equalto', validator_id | string)
        | map(attribute='public_ip_address')
        | first
      }}

- name: Debug validator_id
  debug:
    msg: "Vid: '{{ validator_id }}'"

- name: Set validator address
  set_fact:
    validator_ip: >-
      {{
        groups['snarkos_validator']
        | map('extract', hostvars)
        | selectattr('tags.Dev', 'equalto', validator_id | string)
        | map(attribute='public_ip_address')
        | first
      }}

- name: Set own address
  set_fact:
    own_address: "{{ hostvars[inventory_hostname]['public_ip_address'] }}"

- name: Collect client addresses, filtering out own_address
  set_fact:
    client_addresses: >-
      {{
        groups['snarkos_client']
        | map('extract', hostvars)
        | map(attribute='public_ip_address')
        | select('ne', own_address)
        | shuffle
      }}

- name: slice 7 from client_addresses
  set_fact:
    client_addresses: "{{ client_addresses[:7] }}"

- name: Append port :4130 to client addresses
  set_fact:
    client_addresses: "{{ client_addresses | join(',') | regex_replace('([^,]+)', '\\1:4130') }}"

- name: Set node_id based on instance tag
  set_fact:
    node_id: "{{ (num_instances | int) + 100*(validator_id | int) + 10000*(tags['Dev'] | int) }}"

- name: Assert that num_instances is lower than 100
  assert:
    that:
      - (num_instances | int) < 100
    fail_msg: "The client node_id indexing assumes less than 100 validators."

- name: Set snarkos command with the assigned validator
  set_fact:
    snarkos_command: >-
      snarkos start --client --nocdn --nodisplay \
        --rest 0.0.0.0:3030 --node 0.0.0.0:4130 \
        --verbosity {{ snarkos_verbosity }} --metrics \
        --peers {{ validator_ip }}:4130,{{ client_addresses }} \
        --dev {{ node_id }} --dev-num-validators {{ num_instances }} \
        --rest-rps {{ rest_rps }}  --network {{ snarkos_network_int }}
