- name: Wait for SSH to become available
  hosts: all
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - name: Wait for SSH to become ready
      wait_for_connection:

- name: Check which installation method is used
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if a local pre-built version should be used
      set_fact:
        use_local_pre_build: >-
          {{
            (snarkos_pre_build_location is defined and snarkos_pre_build_location | length > 0)
          }}

    - name: Check if S3 pre-built version should be used
      set_fact:
        use_s3_pre_build: >-
          {{
            (snarkos_pre_build_location is undefined) and
            (s3_bucket is defined and s3_bucket | length > 0) and
            (use_snarkos_pre_build_s3 is defined and use_snarkos_pre_build_s3|bool)
          }}

    - name: Check if local build should be used
      set_fact:
        use_local_build: >-
          {{
            (snarkos_pre_build_location is undefined) and
            (use_snarkos_pre_build_s3 is undefined or not use_snarkos_pre_build_s3|bool) and
            (snarkos_repo is defined and snarkos_repo | length > 0) and
            (snarkos_git_commit_local_build is defined and snarkos_git_commit_local_build | length > 0)
          }}

    - name: Check if GitHub build should be used
      set_fact:
        use_github_build: >-
          {{
            (snarkos_pre_build_location is undefined) and
            (use_snarkos_pre_build_s3 is undefined or not use_snarkos_pre_build_s3|bool) and
            (snarkos_binary_tag is defined and snarkos_binary_tag | length > 0)
          }}

    - name: Check if remote build should be used
      set_fact:
        use_remote_build: >-
          {{
            (snarkos_pre_build_location is undefined) and
            (use_snarkos_pre_build_s3 is undefined or not use_snarkos_pre_build_s3|bool) and
            (snarkos_git_hash is defined and snarkos_git_hash | length > 0) and
            (snarkos_repo is defined and snarkos_repo | length > 0)
          }}

    - name: Check malice download method
      set_fact:
        use_malicious_snarkos_pre_build: >-
          {{
            (use_malicious_snarkos_pre_build is defined) and (use_malicious_snarkos_pre_build|bool)
          }}

    - name: Ensure exactly one installation method is used
      fail:
        msg: "Exactly one installation method should be used."
      when: (use_local_build | int + use_github_build | int + use_remote_build | int | int + use_local_pre_build | int + use_s3_pre_build) != 1

- name: Build and upload snarkOS to S3 if required
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Build and upload snarkOS to S3
      include_role:
        name: snarkos_build_locally
      when: hostvars['localhost'].use_local_build

# ------------------------------------------------
# snarkOS installation

- name: Install snarkOS
  hosts: snarkos*
  become: true
  remote_user: ubuntu
  vars:
    s3_bucket: "{{ s3_bucket }}"
    snarkos_pre_build_location: "{{ snarkos_pre_build_location }}"
    snarkos_git_hash: "{{ hostvars['localhost'].snarkos_git_hash }}"
    release_name: "{{ hostvars['localhost'].releasename | default('snarkos') }}"
    dest_name: "snarkos"
  tasks:
    - name: Use local pre-built version
      include_role:
        name: snarkos_upload_local
      when: hostvars['localhost'].use_local_pre_build

    - name: Install snarkOS from S3
      include_role:
        name: snarkos_install_s3
      when: hostvars['localhost'].use_s3_pre_build or hostvars['localhost'].use_local_build

    - name: Install snarkOS from binary
      include_role:
        name: snarkos_install_binary
      when: hostvars['localhost'].use_github_build

    - name: Build snarkOS from git
      include_role:
        name: snarkos_build_from_git
      when: hostvars['localhost'].use_remote_build

    - name: Download malice snarkOS binary with GitHub CLI
      shell: >
        TAG="{{ snarkos_malice_tag }}"

        apt-get install -y unzip

        GITHUB_TOKEN="{{ github_token }}" gh release download ${TAG}
        --repo ProvableHQ/snarkOS-staging
        --pattern "snarkos*unknown-linux-gnu.zip"
        --output "/tmp/snarkos-malicious.zip"
        --clobber

        unzip -o /tmp/snarkos-malicious.zip -d /tmp/snarkos-malicious

        mv /tmp/snarkos-malicious/snarkos /usr/bin/snarkos-malice
      args:
        executable: /bin/bash
      when: not hostvars['localhost'].use_malicious_snarkos_pre_build

    - name: Download malice snarkOS binary from S3
      vars:
        release_name: "{{snarkos_malice_tag}}/snarkos"
        dest_name: "snarkos-malice"
      include_role:
        name: snarkos_install_s3
      when: hostvars['localhost'].use_malicious_snarkos_pre_build

  tags: snarkos_install

# ------------------------------------------------
# zip
- name: Install zip 
  hosts: snarkos*
  become: true
  remote_user: ubuntu
  tasks:
    - name: Install zip
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - zip
      retries: 20
      delay: 30
      until: apt_result is success

# ------------------------------------------------
# flamegraph

- name: Install flamegraph dependencies
  hosts: snarkos_validator
  become: true
  remote_user: ubuntu
  pre_tasks:
    - include_tasks: set_validator_facts.yml
  tasks:
    - name: Capture kernel version
      command: uname -r
      register: kernel_version
      when: create_flamegraph

    - name: Install flamegraph dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - linux-tools-common
        - linux-tools-generic
        - linux-tools-{{ kernel_version.stdout }}
        - build-essential
      retries: 20
      delay: 30
      until: apt_result is success
      when: create_flamegraph
  
    - name: Install Rustup and flamegraph # As advised by https://github.com/flamegraph-rs/flamegraph
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

        . "$HOME/.cargo/env"

        cargo install flamegraph
      args:
        executable: /bin/bash
      when: create_flamegraph

# ------------------------------------------------
# snarkOS Process Exporter

- name: Install and Configure Process Exporter
  hosts: snarkos*
  become: true
  remote_user: ubuntu
  roles:
    - process_exporter_setup
  tags: process_exporter

# ------------------------------------------------
# snarkOS Node Exporter

- name: Install and Configure Node Exporter
  hosts: snarkos*
  become: true
  remote_user: ubuntu
  roles:
    - node_exporter_setup
  tags: node_exporter

# ------------------------------------------------
# Logstash

- name: Install and Configure Logstash
  hosts: snarkos*
  become: true
  remote_user: ubuntu
  pre_tasks:
    - include_tasks: logging_enrichment.yml
      vars:
        use_local_pre_build: "{{ hostvars['localhost'].use_local_pre_build }}"
        use_s3_pre_build: "{{ hostvars['localhost'].use_s3_pre_build }}"
        use_local_build: "{{ hostvars['localhost'].use_local_build }}"
        use_github_build: "{{ hostvars['localhost'].use_github_build }}"
        use_remote_build: "{{ hostvars['localhost'].use_remote_build }}"
        snarkos_git_hash: "{{ hostvars['localhost'].snarkos_git_hash }}"

  roles:
    - logstash_setup
  tags: logstash

# ------------------------------------------------
# Metricbeat

- name: Install and Configure Metricbeat
  hosts: snarkos*
  become: true
  remote_user: ubuntu
  pre_tasks:
    - include_tasks: logging_enrichment.yml
      vars:
        use_local_pre_build: "{{ hostvars['localhost'].use_local_pre_build }}"
        use_s3_pre_build: "{{ hostvars['localhost'].use_s3_pre_build }}"
        use_local_build: "{{ hostvars['localhost'].use_local_build }}"
        use_github_build: "{{ hostvars['localhost'].use_github_build }}"
        use_remote_build: "{{ hostvars['localhost'].use_remote_build }}"
        snarkos_git_hash: "{{ hostvars['localhost'].snarkos_git_hash }}"
  roles:
    - metricbeat_setup
  tags: metricbeat

# ------------------------------------------------
# Filebeat

- name: Install and Configure Filebeat
  hosts: snarkos*
  become: true
  remote_user: ubuntu
  pre_tasks:
    - include_tasks: logging_enrichment.yml
      vars:
        use_local_pre_build: "{{ hostvars['localhost'].use_local_pre_build }}"
        use_s3_pre_build: "{{ hostvars['localhost'].use_s3_pre_build }}"
        use_local_build: "{{ hostvars['localhost'].use_local_build }}"
        use_github_build: "{{ hostvars['localhost'].use_github_build }}"
        use_remote_build: "{{ hostvars['localhost'].use_remote_build }}"
        snarkos_git_hash: "{{ hostvars['localhost'].snarkos_git_hash }}"
  roles:
    - filebeat_setup
  tags: filebeat

# ------------------------------------------------
# Prometheus for Grafana metrics

- name: Install and Configure Prometheus
  hosts: prometheus_server
  become: true
  remote_user: ubuntu
  gather_facts: true
  roles:
    - prometheus_setup_with_clients
  tags: prometheus

# ------------------------------------------------
# snarkOS validators

- name: Set up and start snarkOS network for validators
  hosts: snarkos_validator
  become: true
  remote_user: ubuntu
  pre_tasks:
    - include_tasks: set_validator_facts.yml
  roles:
    - snarkos_service
  tags: snarkos

# ------------------------------------------------
# snarkOS clients

- name: Set up and start snarkOS network for clients
  hosts: snarkos_client
  become: true
  remote_user: ubuntu
  pre_tasks:
    - include_tasks: set_client_facts.yml
  roles:
    - snarkos_service
  tags: snarkos_client

# ------------------------------------------------
# Optionall restart validators if creating a flamegraph to avoid measuring genesis block creation

- name: Optionally restart snarkOS validators
  hosts: snarkos_validator
  become: true
  remote_user: ubuntu
  pre_tasks:
    - include_tasks: set_validator_facts.yml
  tasks:
    - name: Restart snarkOS validators
      systemd:
        name: snarkos
        state: restarted
      when: create_flamegraph
  tags: snarkos
