- name: Prepare controller-side facts (validator data + bootstrap clients)
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tags: always
  tasks:
    - name: Load validator data from JSON
      set_fact:
        validator_data: "{{ lookup('file', playbook_dir + '/../validator_data/data.json') | from_json }}"

    - name: Decide on the bootstrap clients
      ansible.builtin.include_role:
        name: choose_bootstrap_client

- name: Wait for SSH to become available
  hosts: all
  remote_user: ubuntu
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Wait for SSH to become ready
      ansible.builtin.wait_for_connection:

- name: Install shared SSH keys from repo keys.pub
  hosts: all
  become: true
  remote_user: ubuntu
  gather_facts: false
  roles:
    - shared_ssh_keys

# ------------------------------------------------
# snarkOS installation

- name: Install snarkOS
  hosts:
    - snarkos*
    - tx_runner
  become: true
  remote_user: ubuntu
  any_errors_fatal: true
  strategy: free
  vars:
    gcs_bucket: "{{ gcs_bucket | default('provable-binaries-releases') }}"
    snarkos_pre_build_location: "{{ snarkos_pre_build_location }}"
    snarkos_git_hash: "{{ hostvars['localhost'].snarkos_git_hash }}"
    release_name: "{{ hostvars['localhost'].release_name }}"
    dest_name: "snarkos"
  tasks:
    - name: Install snarkOS from GCS
      ansible.builtin.include_role:
        name: snarkos_install_gcs
      vars:
        release_name: "{{ release_name }}"
        snarkos_install_s3_dest_name: "{{ dest_name }}"

  tags: snarkos_install

# ------------------------------------------------
# flamegraph

# - name: Install flamegraph dependencies
#   hosts: snarkos_validator
#   become: true
#   remote_user: ubuntu
#   any_errors_fatal: true
#   pre_tasks:
#     - name: Set Validator Facts
#       ansible.builtin.include_tasks: set_validator_facts.yml
#   tasks:
#     - name: Capture kernel version
#       ansible.builtin.command: uname -r
#       register: kernel_version
#       when: create_flamegraph
#       changed_when: kernel_version is success

#     - name: Install flamegraph dependencies
#       ansible.builtin.apt:
#         name: "{{ item }}"
#         state: present
#         update_cache: true
#       with_items:
#         - linux-tools-common
#         - linux-tools-generic
#         - linux-tools-{{ kernel_version.stdout }}
#         - build-essential
#       retries: 20
#       delay: 30
#       until: apt_result is success
#       when: create_flamegraph

    # - name: Install Rustup and flamegraph # As advised by https://github.com/flamegraph-rs/flamegraph
    #   ansible.builtin.command: |
    #     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    #     . "$HOME/.cargo/env"

    #     cargo install flamegraph
    #   args:
    #     executable: /bin/bash
    #   when: create_flamegraph

# ------------------------------------------------
# Observability setup

- name: Install and Configure Google Cloud Ops Agent
  hosts: snarkos*
  become: true
  remote_user: ubuntu
  any_errors_fatal: true
  strategy: free
  roles:
    - google_ops_agent_setup
  vars:
    ops_agent_commit_id: "{{ snarkos_git_hash | default('') }}"
    ops_agent_branch_name: "{{ snarkos_branch | default('') }}"
    ops_agent_owner: "{{ gcp_labels.owner | default('') }}"
    ops_agent_role: "{{ gcp_labels.role | default('') }}"
    ops_agent_mode: "{{ mode | default('') }}"
    ops_agent_tests: "{{ tests | default('') }}"
    ops_agent_snarkos_network: "{{ snarkos_network | default('') }}"

# ------------------------------------------------
# snarkOS validators

- name: Set up and start snarkOS network for validators
  hosts: snarkos_validator
  become: true
  remote_user: ubuntu
  any_errors_fatal: true
  strategy: free
  vars:
    snarkos_commit_id: "{{ snarkos_git_hash | default('') }}"
    snarkos_branch_name: "{{ snarkos_branch | default('') }}"
  pre_tasks:
    - name: Set Validator facts
      include_tasks: set_validator_facts.yml
  roles:
    - snarkos_service
  tags: snarkos

# ------------------------------------------------
# snarkOS clients

- name: Set up and start snarkOS network for clients
  hosts: snarkos_client
  become: true
  remote_user: ubuntu
  any_errors_fatal: true
  strategy: free
  pre_tasks:
    - name: Set client facts
      include_tasks: set_client_facts.yml
  roles:
    - snarkos_service
  tags: snarkos_client

# ------------------------------------------------
# snarkOS provers

- name: Set up and start snarkOS network for provers
  hosts: snarkos_prover
  become: true
  remote_user: ubuntu
  any_errors_fatal: true
  strategy: free
  pre_tasks:
    - name: Set Prover facts
      include_tasks: set_prover_facts.yml
  roles:
    - snarkos_service
  tags: snarkos

# ------------------------------------------------
# TX Runner

- name: Set up the TX Runner
  hosts: tx_runner
  become: true
  remote_user: ubuntu
  any_errors_fatal: true
  pre_tasks:
  roles:
    - setup_tx_runner
  tags: tx_runner

# ------------------------------------------------
# Optional restart validators if creating a flamegraph to avoid measuring genesis block creation

# - name: Optionally restart snarkOS validators
#   hosts: snarkos_validator
#   become: true
#   remote_user: ubuntu
#   any_errors_fatal: true
#   pre_tasks:
#     - name: Set Validator facts
#       include_tasks: set_validator_facts.yml
#   tasks:
#     - name: Restart snarkOS validators
#       systemd:
#         name: snarkos
#         state: restarted
#       when: create_flamegraph
#   tags: snarkos

# ------------------------------------------------
# Check if the network is advancing and blocks are being produced

- name: Check if the network is advancing
  hosts: snarkos_validator
  become: true
  remote_user: ubuntu
  any_errors_fatal: true
  tasks:
    - name: Fetch the current block height
      ansible.builtin.uri:
        url: "http://{{ test_network_url }}:3030/{{ snarkos_network }}/block/latest"
        method: GET
        return_content: true
      register: current_block
      until: current_block.json is defined
      retries: 10
      delay: 10

    - name: Wait for the network to progress by one block
      ansible.builtin.uri:
        url: "http://{{ test_network_url }}:3030/{{ snarkos_network }}/block/latest"
        method: GET
        return_content: true
      register: next_block
      until: next_block.json['header']['metadata']['height'] | int > current_block.json['header']['metadata']['height'] | int
      retries: 10
      delay: 10
