# Observability keys received from Infra team.
cloud_id: "your_elastic_cloud_id_here"
elastic_api_key: "your_elastic_api_key_here"
grafana_cloud_api_key: "your_grafana_cloud_api_key_here"

# Your own github access token.
github_token: "your_github_token_here" # link to generate: https://github.com/settings/tokens/new?scopes=repo&description=burn-in-testing-snarkos

# Observability infra vars
create_flamegraph: false
flamegraph_node_id: "0" # Validator node ID to generate flamegraph for

# For local build: (leave commented out if using another installation method)
snarkos_git_commit_local_build: "66a4dfbefd5d2a7aa75a62dbe3e98f09d262ea92"
snarkos_repo: "git@github.com:ProvableHQ/snarkOS-staging.git" # note the URL format
envs: "RUST_BACKTRACE=0,CARGO_PROFILE_RELEASE_DEBUG=false" # optional, e.g., "RUST_BACKTRACE=0 CARGO_PROFILE_RELEASE_DEBUG=false"
features: "test_network" # WARNING: if you turn off test_network, tx-cannon may not use the correct consensus versions.

# For GitHub build: (note that it uses the ProvableHQ/snarkOS-staging repository. Comment out if using another installation method)
# snarkos_binary_tag: "mainnet-latest"

# For remote build: (leave commented out if using another installation method)
# snarkos_git_hash: "mainnet-staging" # NOTE: can be a branch name or a commit hash
# snarkos_repo: "https://github.com/ProvableHQ/snarkOS-staging" # note the URL format
# envs: "RUSTFLAGS=--cfg tokio_unstable,RUST_BACKTRACE=0,CARGO_PROFILE_RELEASE_DEBUG=false" # optional, e.g., "RUST_BACKTRACE=0 CARGO_PROFILE_RELEASE_DEBUG=false"
# features: "test_network,tokio_console" # optional

# Other vars
snarkos_malice_tag: "malice-2349f3eda" # NOTE: test_skip_tx_checks feature may cause a fork due to accepting invalid txs. Only GitHub build installation method currently supported.

# Optional vars
# snarkos_git_commit_local_build_update: "73147585924a33ef009a9af949a098941c9a9ea5" # necessary for the update_validators_and_clients_one_by_one test. Should be used together with the local build method.

# Vars to be used with pre-built releases.
# All these vars are use by the auto-builder that is triggered on new releases and shouldn't be used locally.
# Adding them here for documentation purposes:

# To use a snarkos binary put in the root of the configured `s3_bucket`:
# use_snarkos_pre_build_s3: true 
# s3_bucket: '<existing-bucket-containing-the-snarkos-binary>'

# To use malicious SnarkOS pre-built binary located on the configured `s3_bucket` under folder named like the `snarkos_malice_tag`:
# use_malicious_snarkos_pre_build: true 
# s3_bucket: '<existing-bucket-containing-the-malicious-snarkos-binary>'

# To use a local pre-built SnarkOS binary on the given path.
# snarkos_pre_build_location: "/home/ubuntu/bin/snarkos" 

# To change the ECR, region or image tx-cannon is installed from:
# txcannon_ecr_region: 'us-east-1'
# txcannon_ecr_repo: '637423331354.dkr.ecr.us-east-1.amazonaws.com/tx-cannon'
# txcannon_image_tag: '60606a83b4527b9ff11848d591788fdeeacbf08b'

# TXCannon build related vars,
# Make sure it uses the same snarkVM rev as snarkOS:
txcannon_envs: ""
txcannon_features: "test_network"

# Application vars
snarkos_verbosity: "6"
rest_rps: 1000000000

# TX pre-generation variables:
# txs_target_consensus_version: 10
# txs_target_consensus_version_height: 22
# pregeneration_execution_tx_count: 40
# pregeneration_deployment_tx_count: 20
# pregeneration_bucket_path: "pregenerated_transactions"
# pregenerate_transactions_num_validators: 5
# pregeneration_tx_batch_size: 5

# Ansible vars
# ansible_python_interpreter: /usr/bin/python3.10


# Do not change the code below
generate_release_name: "COMMIT_HASH{{ '_' + features if (features is defined and features | length > 0) else '' }}{{ '_' + (envs | regex_replace('=', '_') | regex_replace(' ', '_')) if (envs is defined and envs | length > 0) else '' }}"
