# snarkos_setup.yml
- name: Wait for SSH to become available
  hosts: "tx_cannon_node"
  remote_user: ubuntu
  gather_facts: no
  tasks:
    # TODO: with the chosen machine, this experiences a frequent timeout.
    - name: Wait for SSH to become ready
      ansible.builtin.wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        timeout: 480  # Maximum seconds to wait.  Default is 300.
                      # Increased timeout to 8 minutes based on AWS experience.
        delay: 10  # seconds to wait before starting to poll
        sleep: 2  # number of seconds to sleep between checks.  Default is 1.
        state: started  # 'started' is the default---it just means the port is open
      any_errors_fatal: true  # Don't continue without a full complement of instances

- name: Set up snarkOS and tx-cannon
  hosts: "tx_cannon_node"
  become: yes
  remote_user: ubuntu
  vars:
    verbosity: "1"
    num_validators: 10
  tasks:
    - name: Gather facts from all nodes
      setup:

    - name: Set first node IP address
      set_fact:
        first_node_ip: "{{ hostvars[groups['tx_cannon_node'][0]]['public_ip_address']}}"
      when: groups['tx_cannon_node'] is defined and groups['tx_cannon_node'] | length > 0
      run_once: true

    - name: Set node_id based on instance tag
      set_fact:
        node_id: "{{ tags['Dev'] }}"

    - name: Install GitHub CLI
      shell: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
      args:
        executable: /bin/bash
      become: yes

    - name: Export GitHub token for gh CLI
      ansible.builtin.set_fact:
        gh_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"

    - name: Download snarkOS binary with GitHub CLI 
      shell: >
        TAG=mainnet-staging-latest

        apt-get install -y unzip

        gh release download ${TAG}
        --repo ProvableHQ/snarkOS-staging
        --pattern "snarkos*unknown-linux-gnu.zip"
        --output "/usr/bin/snarkos.zip"
        --skip-existing
  
        unzip -o /usr/bin/snarkos.zip -d /usr/bin
      environment:
        GITHUB_TOKEN: "{{ gh_token }}"
      args:
        executable: /bin/bash
      become: yes

    - name: Make snarkos executable
      file:
        path: "/usr/bin/snarkos"
        mode: '0755'

    - name: Clone or update tx-cannon
      git:
        repo: "https://{{ gh_token }}:x-oauth-basic@github.com/ProvableHQ/tx-cannon.git"
        dest: "/home/ubuntu/tx-cannon"
        version: "mainnet"

    - name: Download tx-cannon binary with GitHub CLI 
      shell: >
        TAG=mainnet-latest

        apt-get install -y unzip
      
        GITHUB_TOKEN="{{ gh_token }}" gh release download ${TAG}
        --repo ProvableHQ/tx-cannon
        --pattern "tx-cannon*unknown-linux-gnu.zip"
        --output "/usr/bin/tx-cannon.zip"
        --skip-existing

        unzip -o /usr/bin/tx-cannon.zip -d /usr/bin
      environment:
        GITHUB_TOKEN: "{{ gh_token }}"
      args:
        executable: /bin/bash
      become: yes

    - name: Make tx-cannon executable
      file:
        path: "/usr/bin/tx-cannon"
        mode: '0755'

    # TODO: the following task can hang, make sure to properly await its completion

    - name: Run tx-cannon and capture logs
      shell: |
        cd /home/ubuntu/tx-cannon
        python3 tests/scripts/tx_pregeneration.py --transaction_type deployment --num_validators {{ num_validators }} --num_transactions {{ num_deployments }} --num_proofs_in_parallel {{ prover_parallelization }} --program_file {{ program_file }} --program_suffix {{ program_suffix }}
      args:
        executable: /bin/bash
      vars:
        program_file: "/home/ubuntu/tx-cannon/tests/1M_constraint_deployment_100_programs_50_nodes/program_original.txt"
        program_suffix: "{{ node_id }}"
        # the default snarkOS rate-limits allow 8 per second for 10 minutes per validator, spread over the different number of tx-cannon workers
        # however, 1000 deployments already cost as much as a month's budget so we go with that
        num_deployments: "{{ (1000 / (groups['tx_cannon_node'] | length)) | float | int }}" 
        prover_parallelization: "5" # suitable for a c5.4xlarge
      become: yes

    - name: Set node_id based on instance tag 2
      set_fact:
        node_id: "{{ tags['Dev'] }}"

    - name: Fetch pregenerated transactions
      fetch:
        src: "/home/ubuntu/tx-cannon/program_deployments/all_deployments.txt"
        dest: "./{{ node_id }}-e347f8636-{{ num_validators }}val-deploys.txt"
        flat: yes
      
