# logstash_setup.yml
- name: Install and Configure Logstash
  hosts: "snarkos_node"
  become: yes
  remote_user: ubuntu

  vars_prompt:
    - name: collection_enpdoint
      prompt: "Enter the OpenSearch or ElasticSearch collection Endpoint (e.g. https://abcdef123456.us-east-1.aoss.amazonaws.com)"
      private: no

    - name: aws_access_key_id
      prompt: "Enter your AWS Access Key ID"
      private: yes

    - name: aws_secret_access_key
      prompt: "Enter your AWS Secret Access Key"
      private: yes

  tasks:
    - name: Set AWS Region Fact
      set_fact:
        aws_region: "{{ ansible_host.split('.')[1] }}"
      when: ansible_host is defined

    - name: Add Elastic GPG key
      ansible.builtin.shell:
        cmd: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --batch --yes --dearmor -o /usr/share/keyrings/elastic-keyring.gpg"

    - name: Add Elastic APT repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/elastic-8.x.list
        line: "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        create: yes
        state: present

    - name: Update and install Logstash
      ansible.builtin.apt:
        update_cache: yes
        name: logstash
        state: latest

    - name: Install Logstash Output Opensearch Plugin
      ansible.builtin.shell:
        cmd: "/usr/share/logstash/bin/logstash-plugin install --version 2.0.0 logstash-output-opensearch"

    - name: Copy Logstash Configuration Template
      ansible.builtin.template:
        src: logstash.conf
        dest: /etc/logstash/conf.d/logstash.conf

    - name: Start Logstash Service
      ansible.builtin.systemd:
        name: logstash
        state: started
        enabled: yes
