# snarkos_start.yml
- name: Start snarkOS nodes
  hosts: "snarkos_node"
  become: yes
  remote_user: ubuntu
  vars:
    branch: "testnet3"
    verbosity: "4"
  tasks:
    - name: Start snarkos service
      systemd:
        name: snarkos
        state: started
        enabled: yes
      become: yes