- name: Set up snarkOS nodes
  hosts: "snarkos_node"
  become: yes
  remote_user: ubuntu
  vars:
    branch: "testnet3"
    verbosity: "4"
  tasks:
    - name: Gather facts from all nodes
      setup:

#    - name: Debug - Print group names and their contents
#      debug:
#        var: groups

    - name: Set first node IP address
      set_fact:
        first_node_ip: "{{ hostvars[groups['snarkos_node'][0]]['ansible_default_ipv4']['address'] }}"
      when: groups['snarkos_node'] is defined and groups['snarkos_node'] | length > 0
      run_once: true

#    - name: Debug - Print first_node_ip
#      debug:
#        var: first_node_ip

    - name: Determine the number of instances
      set_fact:
        num_instances: "{{ groups['snarkos_node'] | length }}"
      run_once: true

    - name: Set node_id for each host
      set_fact:
        node_id: "{{ item.index }}"
      with_indexed_items: "{{ groups['snarkos_node'] }}"
      delegate_to: localhost
      run_once: true


    - name: Clone or update snarkOS
      git:
        repo: 'https://github.com/AleoHQ/snarkOS.git'
        dest: "/home/ubuntu/snarkOS"
        version: "{{ branch }}"
        clone: yes
        update: yes

    - name: Install Ubuntu dependencies
      apt:
        name:
          - build-essential
          - curl
          - clang
          - gcc
          - libssl-dev
          - llvm
          - make
          - pkg-config
          - tmux
          - xz-utils
          - ufw
        update_cache: yes

    - name: Install Rust
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

#    - name: Build snarkOS
#      shell: |
#        export PATH="$HOME/.cargo/bin:$PATH"
#        cd /home/ubuntu/snarkOS
#        cargo install --path .
#      args:
#        executable: /bin/bash

    - name: Open ports on system
      shell: ufw allow "{{ item }}"
      loop:
        - "5000/tcp"
        - "4133/tcp"
        - "3033/tcp"



    - name: Start snarkos
      shell: |
        snarkos start --nodisplay --bft 0.0.0.0:5000 --rest 0.0.0.0:3033 --peers {{ first_node_ip }}:4133 --validators {{ first_node_ip }}:5000 --verbosity {{ verbosity }} --dev {{ node_id }} --dev-num-validators {{ num_instances }}
