# snarkos_setup.yml
- name: Set up snarkOS nodes
  hosts: "snarkos_node"
  become: yes
  remote_user: ubuntu
  vars:
    branch: "testnet3"
    verbosity: "4"
  tasks:
    - name: Gather facts from all nodes
      setup:

#    - name: Debug - Print group names and their contents
#      debug:
#        var: groups

    - name: Set first node IP address
      set_fact:
        first_node_ip: "{{ hostvars[groups['snarkos_node'][0]]['public_ip_address']}}"
      when: groups['snarkos_node'] is defined and groups['snarkos_node'] | length > 0
      run_once: true

#    - name: Debug - Print first_node_ip
#      debug:
#        var: first_node_ip

    - name: Determine the number of instances
      set_fact:
        num_instances: "{{ groups['snarkos_node'] | length }}"
      run_once: true

    - name: Set node_id based on instance tag
      set_fact:
        node_id: "{{ tags['Dev'] }}"
      loop: "{{ groups['snarkos_node'] }}"
      loop_control:
        loop_var: instance

#    - name: Debug - Print first_node_ip
#      debug:
#        var: node_id


    - name: Clone or update snarkOS
      git:
        repo: 'https://github.com/AleoHQ/snarkOS.git'
        dest: "/home/ubuntu/snarkOS"
        version: "{{ branch }}"
        clone: yes
        update: yes

    - name: Install Ubuntu dependencies
      apt:
        name:
          - build-essential
          - curl
          - clang
          - gcc
          - libssl-dev
          - llvm
          - make
          - pkg-config
          - tmux
          - xz-utils
          - ufw
        update_cache: yes

    - name: Install Rust
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Build snarkOS
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cd /home/ubuntu/snarkOS
        cargo install --path .
      args:
        executable: /bin/bash

    - name: Open ports on system
      shell: ufw allow "{{ item }}"
      loop:
        - "5000/tcp"
        - "4133/tcp"
        - "3033/tcp"

    - name: Set environment variables for snarkos service
      set_fact:
        ansible_env:
          FIRST_NODE_IP: "{{ first_node_ip }}"
          VERBOSITY: "{{ verbosity }}"
          NODE_ID: "{{ node_id }}"
          NUM_INSTANCES: "{{ num_instances }}"
      tags: always

    - name: Deploy the snarkos systemd service file
      template:
        src: snarkos.service
        dest: /etc/systemd/system/snarkos.service
      become: yes

    - name: Reload systemd to read new snarkos service file
      systemd:
        daemon_reload: yes
      become: yes

#    - name: Restart snarkos service
#      systemd:
#        name: snarkos
#        state: restarted
#      become: yes