- name: Set bootstrap clients related facts
  hosts: localhost
  any_errors_fatal: true
  roles:
    - choose_bootstrap_client

- name: Fetch logs from validators
  hosts: snarkos_validator
  become: true
  remote_user: ubuntu
  strategy: free
  pre_tasks:
    - name: Set validator facts
      include_tasks: ../../playbooks/set_validator_facts.yml
  tasks:
    - name: Zip logs
      archive:
        path: "/tmp/snarkos.log"
        dest: "/tmp/snarkos.log.gz"
        mode: "0644"

    - name: Fetch logs
      fetch:
        src: "/tmp/snarkos.log.gz"
        dest: "../../log_files/val-{{ node_id }}-{{ ansible_host }}.log.gz"
        flat: true

    - name: Zip consensus progression logs
      archive:
        path: "consensus_timing_block_{{ node_id }}.json"
        dest: "consensus_timing_block_{{ node_id }}.json.gz"
        mode: "0644"
      failed_when: false

    - name: Fetch consensus progression logs
      fetch:
        src: "consensus_timing_block_{{ node_id }}.json.gz"
        dest: "../../log_files/val-{{ node_id }}-{{ ansible_host }}.consensus_timing_block.json.gz"
        flat: true
      failed_when: false
