- name: Print bucket and release name
  debug:
    msg: "s3_bucket: {{ s3_bucket }}, release_name: {{ release_name }}, snarkos_install_s3_dest_name: {{ snarkos_install_s3_dest_name }}"

- name: Download snarkos binary from S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    object: "{{ release_name | trim }}"
    dest: "/usr/bin/{{ snarkos_install_s3_dest_name }}"
    mode: get
  register: s3_download
  retries: 5
  delay: 15
  until: s3_download is not failed

- name: Ensure the download was successful
  fail:
    msg: "Failed to download snarkos binary from S3."
  when: s3_download.failed

- name: Ensure the binary is executable
  file:
    path: "/usr/bin/{{ snarkos_install_s3_dest_name }}"
    mode: '0755'
