[program:tx_runner]
command=/home/ubuntu/venv/bin/python3 /home/ubuntu/tx_runner.py
directory=/home/ubuntu
autostart=true
autorestart=true
stderr_logfile=/home/ubuntu/tx_runner.err.log
stdout_logfile=/home/ubuntu/tx_runner.log
user=ubuntu
environment=PYTHONUNBUFFERED="1"
