global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    origin_prometheus: {{ devnet_name }}
remote_write:
  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
    basic_auth:
      username: 1272055
      password: {{ grafana_cloud_api_key }}
scrape_configs:
  - job_name: 'Process_Exporter_Validators'
    honor_timestamps: true
    scrape_interval: 5m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:

      {% for host in groups.get('snarkos_validator', []) | union(groups.get('snarkos_client', [])) %}

      - targets: ["{{ host }}:9256"]
        labels:
          group: "process_exporter_validators"
          instance_type: "{{ hostvars[host]['instance_type'] }}"
      {% endfor %}

  - job_name: 'Node_Exporter_Validators'
    honor_timestamps: true
    scrape_interval: 5m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:

      {% for host in groups.get('snarkos_validator', []) %}

      - targets: ["{{ host }}:9100"]
        labels:
          group: "node_exporter_validators"
          instance_type: "{{ hostvars[host]['instance_type'] }}"
      {% endfor %}

  - job_name: 'snarkos_validator'
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:

      {% for host in groups.get('snarkos_validator', []) %}

      - targets: ["{{ host }}:9000"]
        labels:
          group: "snarkos_validator"
          instance_type: "{{ hostvars[host]['instance_type'] }}"
      {% endfor %}

  - job_name: 'snarkos_client'
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:

      {% for host in groups.get('snarkos_client', []) %}

      - targets: ["{{ host }}:9000"]
        labels:
          group: "snarkos_client"
          instance_type: "{{ hostvars[host]['instance_type'] }}"
      {% endfor %}

  - job_name: 'Process_Exporter_Clients'
    honor_timestamps: true
    scrape_interval: 5m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:

      {% for host in groups.get('snarkos_client', []) %}

      - targets: ["{{ host }}:9256"]
        labels:
          group: "process_exporter_clients"
          instance_type: "{{ hostvars[host]['instance_type'] }}"
      {% endfor %}

  - job_name: 'Node_Exporter_Clients'
    honor_timestamps: true
    scrape_interval: 5m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:

      {% for host in groups.get('snarkos_client', []) %}

      - targets: ["{{ host }}:9100"]
        labels:
          group: "node_exporter_clients"
          instance_type: "{{ hostvars[host]['instance_type'] }}"
      {% endfor %}


  - job_name: 'test_identity_data'
    honor_timestamps: true
    scrape_interval: 240s
    scrape_timeout: 30s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets: ["{{ custom_metrics_ip }}:3030"]
        labels:
          group: "test_identity_data"
