---
- name: Install python3-venv (required for virtualenv)
  apt:
    name: python3-venv
    state: present
    update_cache: true

- name: Copy requirements.txt
  template:
    src: requirements.txt
    dest: /home/ubuntu/requirements.txt

- name: Ensure virtualenv is installed
  ansible.builtin.pip:
    name: virtualenv
    executable: pip3

- name: Create virtualenv
  ansible.builtin.command:
    cmd: sudo -u ubuntu python3 -m venv /home/ubuntu/venv
    creates: /home/ubuntu/venv

- name: Install dependencies into virtualenv
  ansible.builtin.pip:
    requirements: /home/ubuntu/requirements.txt
    virtualenv: /home/ubuntu/venv

- name: Set snarkOS binary path based on installation method
  set_fact:
    snarkos_bin_path: "{{ '/home/ubuntu/.cargo/bin' if snarkos_git_hash is defined else '/usr/bin' }}"

- name: Upload the TX runner script
  template:
    dest: "/home/ubuntu/tx_runner.py"
    src: "tx_runner.py"
    mode: '0644'

- name: Upload the block scanner script
  template:
    dest: "/home/ubuntu/block_scanner.py"
    src: "block_scanner.py"
    mode: '0644'

- name: Upload the TX runner tasks
  template:
    dest: "/home/ubuntu/tasks.json"
    src: "tasks.json"
    mode: '0644'

- name: Upload the batch deploy script
  template:
    dest: "/home/ubuntu/batch_deploy.py"
    src: "batch_deploy.py"
    mode: '0644'

- name: Upload the batch transfer script
  template:
    dest: "/home/ubuntu/batch_transfer.py"
    src: "batch_transfer.py"
    mode: '0644'

- name: Ensure correct permissions
  file:
    path: "/home/ubuntu/{{ item }}"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  loop:
    - tasks.json
    - batch_deploy.py
    - batch_transfer.py
    - tx_runner.py
    - block_scanner.py

- name: Push programs and data folders to remote runner
  block:
    - name: Copy programs folder
      ansible.builtin.synchronize:
        src: ../programs/
        dest: /home/ubuntu/programs/
        mode: push
        recursive: yes

    - name: Copy validator data folder
      ansible.builtin.synchronize:
        src: ../validator_data/
        dest: /home/ubuntu/validator_data/
        mode: push
        recursive: yes
  delegate_to: localhost
  become: false

- name: Set permissions on copied folders
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: yes
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  loop:
    - /home/ubuntu/programs/
    - /home/ubuntu/validator_data/

- name: Install supervisord
  apt:
    name: supervisor
    state: present
    update_cache: true

- name: Deploy supervisor config for tx_runner
  template:
    src: tx_runner.conf
    dest: /etc/supervisor/conf.d/tx_runner.conf
    mode: '0644'

- name: Deploy supervisor config for block_scanner
  template:
    src: block_scanner.conf
    dest: /etc/supervisor/conf.d/block_scanner.conf
    mode: '0644'

- name: Touch and chown tx_runner logs
  file:
    path: "/home/ubuntu/tx_runner{{ item }}"
    state: touch
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  loop:
    - .log
    - .err.log
    - _block_scanner.log
    - _block_scanner.err.log

- name: Reread supervisor config
  command: supervisorctl reread

- name: Update supervisor config
  command: supervisorctl update

- name: Restart tx_runner via supervisor
  command: supervisorctl restart tx_runner
