- name: check heights
  block:
  - name: Initialize attempt number if undefined
    set_fact:
      attempt_number: 0
    when: attempt_number is undefined

  - name: Print node 
    debug:
      msg: "Node: {{ node_to_check }}"

  - name: Print node to compare
    debug:
      msg: "Node to compare: {{ node_to_compare }}"

  - name: wait 2 minutes
    pause:
      seconds: 120

  - name: Fetch the block from the node
    delegate_to: "{{ node_to_check }}"
    remote_user: ubuntu
    uri:
      url: "http://{{ node_to_check }}:3030/mainnet/block/latest"
      method: GET
      return_content: true
    register: node_current_block
    retries: 10 
    delay: 2 
    until: node_current_block.status == 200

  - name: Fetch the block from the node to compare
    delegate_to: "{{ node_to_compare }}"
    remote_user: ubuntu
    uri:
      url: "http://{{ node_to_compare }}:3030/mainnet/block/latest"
      method: GET
      return_content: true
    register: node_current_block_compare
    retries: 5
    delay: 2
    until: node_current_block_compare.status == 200

  - name: print node current block height
    debug:
      msg: "Node Current Block height: {{ node_current_block.json['header']['metadata']['height'] }}"

  - name: print node to compare current block height
    debug:
      msg: "Node to compare Current Block height: {{ node_current_block_compare.json['header']['metadata']['height'] }}"

  - name: Calculate height difference
    set_fact:
      height_difference: "{{ (node_current_block_compare.json['header']['metadata']['height'] | int) - (node_current_block.json['header']['metadata']['height'] | int) }}"

  - name: Verify height difference is within acceptable range
    fail:
      msg: "Height difference of {{ height_difference }} is not within the acceptable range."
    when: height_difference | int > 5 or height_difference | int < -5

  - name: Set sync successful
    set_fact:
      sync_successful: true
    when:
      - height_difference | int <= 5
      - height_difference | int >= -5

  rescue:
    - name: Retry message
      debug:
        msg: "Attempt {{ attempt_number | default(0) }} failed.  Previous node height: {{ node_current_block_compare.json['header']['metadata']['height'] }}, Current node height: {{ node_current_block.json['header']['metadata']['height'] }}. Retrying..."

    - name: print attempt number 
      debug:
        msg: "Attempt number: {{ attempt_number }}"

    - name: Increment attempt number
      set_fact:
        incremented_attempt_number: "{{ attempt_number | int + 1 }}"

    - name: Print incremented attempt number
      debug:
        msg: "incremented attempt number: {{ incremented_attempt_number }}"

    - name: Wait 10 seconds before retrying
      pause:
        seconds: 10

    - name: print node to check
      debug:
        msg: "Node to check: {{ node_to_check }}"
    
    - name: Rename node_to_check
      set_fact:
        next_node_to_check: "{{ node_to_check }}"

    - name: Print next node to check
      debug:
        msg: "Next node to check: {{ next_node_to_check }}"

    - name: print node to compare
      debug:
        msg: "Node to compare: {{ node_to_compare }}"

    - name: Rename node_to_compare
      set_fact:
        next_node_to_compare: "{{ node_to_compare }}"
    
    - name: print next node to compare
      debug:
        msg: "Next node to compare: {{ next_node_to_compare }}"

    - name: Retry check heights
      include_tasks: check_heights.yml
      vars:
        node_to_check: "{{ next_node_to_check }}"
        node_to_compare: "{{ next_node_to_compare }}"
        attempt_number: "{{ incremented_attempt_number }}"
        retry_delay: 10
      when: attempt_number | int < 270