# ------------------------------------------------
# tx-cannon

# Get load balancer DNS name
- name: Gather information about all ELBs
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get info about all classic ELBs
      community.aws.elb_classic_lb_info:
        names: snarkos-lb
        region: us-west-1
      register: elb_info

    - name: Set DNS name as a fact
      set_fact:
        snarkos_lb_dns: "{{ elb_info.elbs[0].dns_name }}"

    - ansible.builtin.debug:
        msg: "The DNS name of snarkos-lb is {{ snarkos_lb_dns }}"

    - name: Wait for the network to be healthy
      uri:
        url: "http://{{ snarkos_lb_dns }}:3030/mainnet/latest/height"
        method: GET
        status_code: 200
        timeout: 10
      register: result
      until: result.status == 200
      retries: 10
      delay: 10
  tags: tx-cannon

- name: Ensure block height is at least 10 before proceeding with restart test
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch the current block from the load balancer
      uri:
        url: "http://{{ snarkos_lb_dns }}:3030/mainnet/block/latest"
        method: GET
        return_content: true
      register: lb_current_block
      until: (lb_current_block.json['header']['metadata']['height'] | int) >= 10
      retries: 30
      delay: 10
      ignore_errors: yes

    - name: Print LB current block height
      debug:
        msg: "LB Current Block height is now {{ lb_current_block.json['header']['metadata']['height'] }}"

- name: Reset each node one at a time
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Initialize counter
      set_fact:
        counter: 0

    - name: Include validator actions for each validator
      include_tasks: validators_cycle.yml
      loop: "{{ groups['snarkos_node'] }}"
      loop_control:
        loop_var: node
      vars:
        # Calculate the previous node index manually using the counter
        comparison_node: "{{ groups['snarkos_node'][counter | int - 1 if counter | int > 0 else groups['snarkos_node'] | length - 1] }}"
      
    - name: Increment counter
      set_fact:
        counter: "{{ counter | int + 1 }}"
