- name: Wait for SSH to become available
  hosts: all
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - name: Wait for SSH to become ready
      wait_for_connection:

# ------------------------------------------------
# Dependencies

# Commented out since using stress test base AMI
#- name: Dependencies
#  import_playbook: ../../../common/ansible_playbooks/dependencies.yml
#  tags: deps

# ------------------------------------------------
# snarkOS validators

- name: Set up and start snarkOS network for validators
  hosts: snarkos_node
  become: true
  vars_files:
    - vars.yml
  remote_user: ubuntu
  pre_tasks:
    - name: Gather facts from all nodes
      setup:

    - name: Determine the number of instances
      set_fact:
        num_instances: "{{ groups['snarkos_node'] | length }}"
      run_once: true

    - name: Collect and format validator IPs
      set_fact:
        formatted_validator_ips: "{{ groups['snarkos_node'] | map('extract', hostvars, ['public_ip_address']) | map('regex_replace', '^(.*)$', '\\1:5000') | join(',') }}"
      run_once: true

    - name: Calculate index for slicing client IPs
      set_fact:
        start_index: "{{ (groups['snarkos_node'].index(inventory_hostname) * 3) | int % (groups['snarkos_client_node'] | length) }}"
      run_once: false

    - name: Collect client IPs in order
      set_fact:
        all_client_ips: "{{ groups['snarkos_client_node'] | map('extract', hostvars, ['public_ip_address']) | list }}"
      run_once: true

    - name: Assign 3 unique client IPs per validator
      set_fact:
        selected_client_ips: "{{ all_client_ips[start_index|int : (start_index|int + 3)] }}"

    - name: Debug all client IPs
      debug:
        msg: "All client IPs: {{ all_client_ips }}"
    
    - name: Debug my client IPs
      debug:
        msg: "My client IPs: {{ selected_client_ips }}"

    - name: Collect and format client IPs
      set_fact:
        formatted_client_ips: "{{ selected_client_ips | map('regex_replace', '^(.*)$', '\\1:4130') | join(',') }}"

    - name: Debug selected client IPs
      debug:
        msg: "Validator {{ inventory_hostname }} has been assigned the following client IPs: {{ selected_client_ips }}"

    - name: Set node_id based on instance tag
      set_fact:
        node_id: "{{ tags['Dev'] }}"

    - name: Set snarkos command with peers and validators
      set_fact:
        snarkos_command: "snarkos start --metrics --nodisplay --bft 0.0.0.0:5000 --rest 0.0.0.0:3030 --peers {{ formatted_client_ips }} --validators {{ formatted_validator_ips }} --verbosity 1 --dev {{ node_id }} --dev-num-validators {{ num_instances }} --validator --rest-rps 90000000 --no-dev-txs"
    - name: Debug snarkos command
      debug:
        msg: "The snarkos command for this client is: {{ snarkos_command }}"
  roles:
    - snarkos_custom_command_setup
  tags: snarkos



# ------------------------------------------------
# snarkOS clients

- name: Set up and start snarkOS network for clients
  hosts: snarkos_client_node
  become: true
  vars_files:
    - vars.yml
  remote_user: ubuntu
  pre_tasks:
    - name: Gather facts from all nodes
      setup:

    - name: Determine the number of instances
      set_fact:
        num_instances: "{{ groups['snarkos_node'] | length }}"
      run_once: true

    - name: Set node_id based on instance tag
      set_fact:
        node_id: "{{ tags['Dev'] }}"

    - name: Set snarkos command with the assigned validator
      set_fact:
        snarkos_command: "snarkos start --client --nocdn --nodisplay --rest 0.0.0.0:3030 --bft 0.0.0.0:5000 --node 0.0.0.0:4130 --verbosity 1 --metrics --dev {{ node_id }} --dev-num-validators {{ num_instances }} --rest-rps 10000000"

    - name: Debug snarkos command
      debug:
        msg: "The snarkos command for this client is: {{ snarkos_command }}"
  roles:
    - snarkos_custom_command_setup
  tags: snarkos_client_node
# ------------------------------------------------
# snarkOS Process Exporter

- name: Install and Configure Process Exporter
  hosts: snarkos_node
  become: true
  remote_user: ubuntu
  roles:
    - process_exporter_setup
  tags: process_exporter

# ------------------------------------------------
# Logstash

- name: Install and Configure Logstash
  hosts: snarkos_node:snarkos_client_node
  become: true
  vars_files:
    - vars.yml
  remote_user: ubuntu
  pre_tasks:
    - name: Slurp the commit hash
      ansible.builtin.slurp:
        src: /usr/bin/SNARKOS_COMMIT_HASH
      register: file_content_encoded

    - name: Decode the file commit from base64
      set_fact:
        commit_hash: "{{ file_content_encoded['content'] | b64decode | trim }}"

    - name: Set host_public_ip
      set_fact:
        host_public_ip: "{{ hostvars[inventory_hostname]['public_ip_address'] }}"

    - name: Set node_id based on instance tag
      set_fact:
        node_id: "{{ tags['Dev'] }}"
  roles:
    - logstash_setup
  tags: logstash

# ------------------------------------------------
# Prometheus for Grafana metrics

- name: Install and Configure Prometheus
  hosts: prometheus_server
  become: true
  vars_files:
    - vars.yml
  remote_user: ubuntu
  gather_facts: true
  roles:
    - prometheus_setup_with_clients
  tags: prometheus