---
- name: Copy Logstash Configuration Template for snarkOS
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
    mode: "0664"

- name: Copy Logstash Service file
  ansible.builtin.template:
    src: logstash.service
    dest: /lib/systemd/system/logstash.service
    mode: "0664"

- name: Restart Logstash service
  systemd:
    name: logstash
    state: restarted
    daemon_reload: true
  become: true
