---
- name: Ensure Docker service is started
  service:
    name: docker
    state: started

- name: Copy Node Exporter docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /home/ubuntu/docker-compose-node-exporter.yml
    owner: ubuntu
    group: ubuntu
    mode: '0664'
  become: true
  become_user: ubuntu

- name: Run docker-compose up # noqa: no-changed-when
  command:
    cmd: docker-compose -f docker-compose-node-exporter.yml up -d --force-recreate
    chdir: /home/ubuntu/
