- name: Prepare controller-side facts (validator data + bootstrap clients)
  hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  tags: always
  tasks:
    - name: Load validator data from JSON
      set_fact:
        validator_data: "{{ lookup('file', playbook_dir + '/../validator_data/data.json') | from_json }}"

    - name: Decide on the bootstrap clients
      ansible.builtin.include_role:
        name: choose_bootstrap_client

- import_playbook: ../utils/{{ utility_name }}/run_utility.yml
