- name: Set up and run tx-cannon
  hosts: tx_cannon_node
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Execute TX-Cannon Command with dynamic SnarkOS Validator Node IP
      shell: |
        cd /home/ubuntu &&
        /usr/bin/tx-cannon batch-execute --test attack_manifest.toml -e http://{{ test_network_url }}:3030 >> tx-cannon.log 2>&1
      # Removed async and poll to ensure the task completes before moving to fetch logs

    - name: Fetch TX-Cannon Logs
      fetch:
        src: "/home/ubuntu/tx-cannon.log"
        dest: "./tx-cannon-logs/{{ inventory_hostname }}-tx-cannon.log"
        flat: yes
      # Fetches the logs after the command execution completes
