- name: Install prometheus and enable remote forwarding to Grafana cloud
  hosts: prometheus_server
  become: yes 
  gather_facts: true 
  vars:
    ansible_user: ubuntu 
  vars_prompt:
    - name: devnet_name
      prompt: "Input desired devnet name (e.g. 'howard_devnet')"
      private: false
    - name: grafana_cloud_api_key
      prompt: "Paste the grafana cloud api key"
      private: true

  tasks:
    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml  
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu 
        group: ubuntu  
      become_user: ubuntu

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: "/usr/local/bin/docker-compose"
        mode: 'u+x,g+x'

    - name: Create YAML scrape target file of all nodes
      ansible.builtin.template:
        src: prometheus-cloud-grafana.yml 
        dest: /home/ubuntu/prometheus.yml

    - name: Install unzip
      ansible.builtin.package:
        name: unzip
        state: present

    - name: Download, unzip, and set execute permissions on Grafana Agent
      ansible.builtin.shell: |
        curl -O -L "https://github.com/grafana/agent/releases/latest/download/grafana-agent-linux-amd64.zip" &&
        unzip "grafana-agent-linux-amd64.zip" &&
        chmod a+x grafana-agent-linux-amd64
      args:
        chdir: /home/ubuntu
        creates: grafana-agent-linux-amd64

    - name: Run docker-compose up
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/

    - name: Pass devnet name onto template
      set_fact:
        devnet_name: "{{ devnet_name }}"
      delegate_to: localhost
      delegate_facts: true

- name: Template the Grafana Dashboard
  hosts: localhost
  gather_facts: true 
  tasks:
    - name: Template the Grafana Json
      ansible.builtin.template:
        src: grafana-dashboard-template.json
        dest: grafana-dashboard.json


