# snarkos.aws_ec2.yml
plugin: amazon.aws.aws_ec2

regions:
  - us-east-2

keyed_groups:
  - key: tags.Role
    prefix: ""
    separator: ""
    value: "snarkos-node"
  - key: tags.Role
    prefix: ""
    separator: ""
    value: "prometheus-server"

filters:
  instance-state-name: running
  tag:Name: 
    - snarkos-node-*
    - prometheus-server

