input {
  file {
    path => "/tmp/snarkos.log"
    start_position => "beginning"
    codec => multiline {
      pattern => "^%{TIMESTAMP_ISO8601}"
      negate => true
      what => "previous"
    }
  }
}
filter {
  grok {
    match => { "message" => "^%{TIMESTAMP_ISO8601:timestamp}\s+%{LOGLEVEL:loglevel}\s+%{GREEDYDATA:message}" }
    overwrite => [ "message" ]
  }
  date {
    match => [ "timestamp", "ISO8601" ]
  }
}
output {
  elasticsearch {
    index => "snarkos-logs-{{ devnet_name }}-%{+YYYY.MM.dd}"
    cloud_id => "{{ cloud_id }}"
    api_key => "{{ api_key }}"
  }
}