# Observability keys received from Infra team.
cloud_id: "{{ elastic_cloud_id }}"
elastic_api_key: "{{ elastic_api_key }}"
grafana_cloud_api_key: "{{ grafana_cloud_api_key }}"

# Your own github access token.
github_token: "your_github_token_here" # link to generate: https://github.com/settings/tokens/new?scopes=repo&description=burn-in-testing-snarkos

# Observability infra vars
create_flamegraph: false
flamegraph_node_id: "0" # Validator node ID to generate flamegraph for

s3_bucket: "{{ releases_bucket }}"

# Other vars
snarkos_malice_tag: "malice-2349f3eda-with-batch-transmission-request-and-txcache-skip-tx-checks" # NOTE: test_skip_tx_checks feature may cause a fork due to accepting invalid txs. Only GitHub build installation method currently supported.

# Make sure it uses the same snarkVM rev as snarkOS:
txcannon_envs: ""
txcannon_features: "test_network"

use_snarkos_pre_build_s3: true
use_prebuild_tx_cannon: true
use_malicious_snarkos_pre_build: true

# Application vars
snarkos_verbosity: "6"
rest_rps: 1000000000

test_runner_ip: {{ builder_ip }}

txs_target_consensus_version: 10

# Custom scripts
{% raw %}
patch_script_path: "{{ playbook_dir }}/../scripts/patch_snarkvm.sh"
{% endraw %}
