# logstash_logs.yml
- name: View Logstash Service Logs
  hosts: "snarkos_node"
  become: yes
  remote_user: ubuntu

  tasks:
    - name: Get last few logs of Logstash service
      ansible.builtin.command: "journalctl -u logstash --no-pager -n 50"
      register: logstash_logs

    - name: Print Logstash logs
      ansible.builtin.debug:
        msg: "{{ logstash_logs.stdout_lines }}"
