filebeat.inputs:
  - type: journald
    id: snarkos-journald
    include_matches:
      - "_SYSTEMD_UNIT=snarkos.service"

fields_under_root: true
fields:
  node_public_ip: "{{ host_public_ip | default('unknown') }}"
  commit_hash: "{{ commit_hash | default('unknown') }}"
  {% for key, value in tags.items() %}
tags_{{ key | lower }}: "{{ value }}"
  {% endfor %}

output.elasticsearch:
  index: "snarkos-journald-{{ devnet_name | lower }}"
  api_key: "{{ elastic_api_key }}"

cloud.id: "{{ cloud_id }}"

setup.template.name: "snarkos-journald"
setup.template.pattern: "snarkos-journald-*"