- name: Prepare release for S3 and local build
  block:
    - name: Debug envs variable
      debug:
        var: envs

    - name: Parse envs into a dictionary using dict filter
      set_fact:
        envs_dict: "{{ dict(envs | default('') | split(' ') | map('split', '=', 1)) }}"
      when: envs is defined and envs | length > 0

    - name: Debug envs_dict
      debug:
        var: envs_dict

    - name: Set release name
      set_fact:
        releasename: "{{ generate_release_name | replace('COMMIT_HASH', snarkos_git_commit_to_build) | trim }}"

    - name: Debug generated release name
      debug:
        msg: "Release name: '{{ releasename }}'"

    - name: Check if the binary for the git hash exists in S3 bucket
      aws_s3:
        bucket: "{{ s3_bucket }}"
        mode: list
        prefix: "{{ releasename }}"
        profile: "{{ s3_profile }}"
      register: s3_ls_output
      failed_when: false

    - name: Set fact if object exists
      set_fact:
        s3_binary_exists: "{{ releasename in (s3_ls_output.s3_keys | default([])) }}"

    - name: Fail if compiling with the 'locktick' feature on macOS - cross-compilation is not supported
      fail:
        msg: "Compiling with the 'locktick' feature is not supported on macOS. Please remove it from the features variable."
      when: not s3_binary_exists and ansible_system == 'Darwin' and features is defined and 'locktick' in features

    - name: Construct authenticated repo URL if GitHub token is set
      set_fact:
        effective_snarkos_repo: >-
          {{
            snarkos_repo | regex_replace('https://', 'https://' ~ github_token ~ '@')
            if github_token is defined and github_token != '' and github_token != 'your_github_token_here'
            else snarkos_repo
          }}
      when: not s3_binary_exists

    - name: Clone the repository if the binary is not found in S3
      git:
        repo: "{{ effective_snarkos_repo }}"
        dest: "{{ clone_dir_base }}/{{ snarkos_git_commit_to_build }}"
        version: "{{ snarkos_git_commit_to_build }}"
        depth: 1
        force: true
      when: not s3_binary_exists

    - name: Override Rust version (macOS only)
      shell: cd {{ clone_dir_base }}/{{ snarkos_git_commit_to_build }} && rustup override set nightly-aarch64-apple-darwin
      when:
        - not s3_binary_exists
        - ansible_system == 'Darwin'

    - name: Check if OpenSSL is installed
      stat:
        path: "{{ openssl_install_prefix }}"
      register: openssl_stat

    - name: Create tmp directory for building OpenSSL
      file:
        path: "{{ clone_dir_base }}/{{ snarkos_git_commit_to_build }}/tmp"
        state: directory
        mode: '0755'
      when:
        - not s3_binary_exists
        - ansible_system == 'Darwin'
        - not openssl_stat.stat.isdir

    - name: Download OpenSSL tarball
      get_url:
        url: "{{ openssl_url }}"
        dest: "{{ clone_dir_base }}/{{ snarkos_git_commit_to_build }}/tmp/{{ openssl_tarball }}"
        mode: '0755'
      when:
        - not s3_binary_exists
        - ansible_system == 'Darwin'
        - not openssl_stat.stat.isdir

    - name: Extract OpenSSL tarball using tar command
      command: tar -xzf "{{ openssl_tarball }}"
      args:
        chdir: "{{ clone_dir_base }}/{{ snarkos_git_commit_to_build }}/tmp"
      when:
        - not s3_binary_exists
        - ansible_system == 'Darwin'
        - not openssl_stat.stat.isdir

    - name: Configure OpenSSL
      command: >
        ./Configure linux-x86_64 no-shared no-module no-dso no-async
        --prefix={{ openssl_install_prefix }}
        --openssldir={{ openssl_install_prefix }}
      args:
        chdir: "{{ clone_dir_base }}/{{ snarkos_git_commit_to_build }}/tmp/{{ openssl_dir }}"
      environment:
        CROSS_COMPILE: "x86_64-unknown-linux-gnu-"
        CFLAGS: "-fPIC -fPIE -pie"
      when:
        - not s3_binary_exists
        - ansible_system == 'Darwin'
        - not openssl_stat.stat.isdir

    - name: Build OpenSSL with make -j12
      command: make -j12
      args:
        chdir: "{{ clone_dir_base }}/{{ snarkos_git_commit_to_build }}/tmp/{{ openssl_dir }}"
      when:
        - not s3_binary_exists
        - ansible_system == 'Darwin'
        - not openssl_stat.stat.isdir

    - name: Install OpenSSL
      command: make install
      args:
        chdir: "{{ clone_dir_base }}/{{ snarkos_git_commit_to_build }}/tmp/{{ openssl_dir }}"
      when:
        - not s3_binary_exists
        - ansible_system == 'Darwin'
        - not openssl_stat.stat.isdir

    - name: Set features flag
      set_fact:
        featureflags: >-
          {{
            "" if (features is not defined or features | length == 0)
            else "--features {{ features }}"
          }}

    - name: Download and modify snarkvm consensus versions
      shell: "{{ patch_script_path }} {{ snarkos_network }}"
      args:
        executable: /bin/bash
        chdir: "{{ clone_dir_base }}/{{ snarkos_git_commit_to_build }}"
      when: not s3_binary_exists

    - name: Check if the folders are too old (including the cache)
      ansible.builtin.find:
        paths: "{{ clone_dir_base }}"
        age: 30d
        age_stamp: mtime
        file_type: directory
      register: old_dirs

    - name: Delete old source folders
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_dirs.files }}"

    - name: Ensure the shared target directory exists
      ansible.builtin.file:
        path: "{{ clone_dir_base }}/shared"
        state: directory
        mode: '0755'

    - name: Enable locktick build features in Cargo.tml
      shell: |
        tmp="$(mktemp)"
        sed 's/^# debug = "line-tables-only"/debug = "line-tables-only"/' Cargo.toml > "$tmp"
        mv "$tmp" Cargo.toml
        sed 's/^# strip = "none"/strip = "none"/' Cargo.toml > "$tmp"
        mv "$tmp" Cargo.toml
      args:
        executable: /bin/bash
        chdir: "{{ clone_dir_base }}/{{ snarkos_git_commit_to_build }}"
      when: not s3_binary_exists and features is defined and 'locktick' in features and ansible_system != 'Darwin'

    - name: Build the Rust project with OpenSSL (macOS)
      command: cargo build --release --target x86_64-unknown-linux-gnu {{ featureflags }}
      args:
        chdir: "{{ clone_dir_base }}/{{ snarkos_git_commit_to_build }}"
      environment: >-
        {{
          {
            'OPENSSL_INCLUDE_DIR': openssl_install_prefix + '/include',
            'OPENSSL_LIB_DIR': openssl_install_prefix + '/lib64',
            'OPENSSL_STATIC': '1',
            'CARGO_TARGET_DIR': '../shared',
            'CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER': 'x86_64-unknown-linux-gnu-gcc'
          } | combine(envs_dict | default({}))
        }}
      register: build_output_mac
      when:
        - not s3_binary_exists
        - ansible_system == 'Darwin'

    - name: Build the Rust project (Linux)
      shell: source "$HOME/.cargo/env" && cargo build --release {{ featureflags }}
      args:
        chdir: "{{ clone_dir_base }}/{{ snarkos_git_commit_to_build }}"
        executable: /bin/bash
      environment:
        CARGO_TARGET_DIR: "../shared"
      register: build_output
      when:
        - not s3_binary_exists
        - ansible_system != 'Darwin'

    - name: Debug build_output_mac
      debug:
        var: build_output_mac

    - name: Debug build_output
      debug:
        var: build_output

    - name: Upload the built snarkos binary to S3 (macOS)
      aws_s3:
        bucket: "{{ s3_bucket }}"
        object: "{{ releasename | trim }}"
        src: "{{ clone_dir_base }}/shared/x86_64-unknown-linux-gnu/release/snarkos"
        mode: put
        profile: "{{ s3_profile }}"
      when:
        - not s3_binary_exists
        - ansible_system == 'Darwin'
      register: s3_upload_output

    - name: Upload the built snarkos binary to S3 (Linux)
      aws_s3:
        bucket: "{{ s3_bucket }}"
        object: "{{ releasename | trim }}"
        src: "{{ clone_dir_base }}/shared/release/snarkos"
        mode: put
        profile: "{{ s3_profile }}"
      when:
        - not s3_binary_exists
        - ansible_system != 'Darwin'
      register: s3_upload_output

    - name: Debug message after upload
      debug:
        msg: "Uploaded snarkos binary to S3."
      when: s3_upload_output.changed

    - name: Set snarkos_git_hash fact for later use
      set_fact:
        snarkos_git_hash: "{{ snarkos_git_commit_to_build }}"
