---
- name: Deploy the tx-cannon systemd service file
  template:
    src: tx-cannon.service
    dest: /etc/systemd/system/tx-cannon.service
    mode: '0644'
  become: true

- name: Reload systemd to read new tx-cannon service file
  systemd:
    daemon_reload: true
  become: true

- name: Restart tx-cannon service
  systemd:
    name: tx-cannon
    state: restarted
  become: true
