version: '3.8'

services:
  process-exporter:
    image: ncabatoff/process-exporter
    command: ["--procfs", "/host/proc", "-procnames", "snarkos"]
    volumes:
      - /proc:/host/proc
      - .:/config
    ports:
      - "9256:9256"
    privileged: true
    restart: unless-stopped
