---
- name: Copy Logstash Configuration Template for snarkOS
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
    mode: "0664"

- name: Restart Logstash service
  systemd:
    name: logstash
    state: restarted
  become: true
