- name: Setup the stress testing manager machine
  hosts: all
  become: true
  gather_facts: true
  remote_user: ubuntu
  become_user: ubuntu
  tasks:
    - name: Read additional authorized keys from the template
      set_fact:
        extra_keys_raw: "{{ lookup('file', 'templates/extra_keys.pub') }}"

    - name: Parse keys into a list
      set_fact:
        extra_keys_list: "{{ extra_keys_raw.splitlines() | select('match', '^ssh-') | list }}"

    - name: Add each key if not already present
      ansible.posix.authorized_key:
        user: "ubuntu"
        key: "{{ item }}"
        state: present
      loop: "{{ extra_keys_list }}"

    - name: Clone the stress-testing repository
      git:
        repo: "https://{{ github_token }}@github.com/ProvableHQ/snarkos-stress-testing.git"
        dest: "/home/ubuntu/stress_testing"
        version: "{{ stress_testing_branch | default('main') }}"
        force: true

    - name: Update APT package index and install dependencies
      become: true
      become_user: root
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - jq
          - python3-pip
          - python3-venv
          - build-essential
          - curl
          - pkg-config
          - libssl-dev
          - libssh2-1-dev
          - clang
          - libclang-dev
          - llvm-dev
          - pkg-config
          - lld
          - cmake
          - wget

    - name: Ensure Python boto3 is installed
      pip:
        name: boto3
        state: present
        executable: pip3

    - name: Download rustup-init script
      become: false
      run_once: false
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh
        mode: '0755'

    - name: Run rustup-init.sh to install Rust and Cargo
      become: false
      run_once: false
      ansible.builtin.command: >
        /tmp/rustup-init.sh -y --no-modify-path
      environment:
        CARGO_HOME: /home/ubuntu/.cargo
        RUSTUP_HOME: /home/ubuntu/.rustup
        HOME: /home/ubuntu
      args:
        creates: /home/ubuntu/.cargo/bin/cargo
      register: rustup_result
      changed_when: "'Rust is installed now' in rustup_result.stdout or rustup_result.rc == 0"
      become_user: ubuntu

    - name: Add Cargo to PATH in .bashrc
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export PATH="$HOME/.cargo/bin:$PATH"'
        insertafter: EOF
      become: false
      become_user: ubuntu

    - name: Add Cargo to PATH for this session
      shell: |
        source $HOME/.cargo/env
        echo $PATH
      args:
        executable: /bin/bash
      register: cargo_path

    - name: Show cargo path
      debug:
        var: cargo_path.stdout

    - name: Check if sccache exists
      stat:
        path: /usr/local/bin/sccache
      register: sccache

    - name: Install sccache
      shell: |
        wget https://github.com/mozilla/sccache/releases/download/v0.10.0/sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz
        tar -xf sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz
        sudo install -m 0755 sccache-*/sccache /usr/local/bin/sccache
      when: not sccache.stat.exists
      args:
        executable: /bin/bash

    - name: Clone the Talisker repository
      git:
        repo: "https://{{ github_token }}@github.com/ProvableHQ/talisker.git"
        dest: "/home/ubuntu/talisker-src"
        version: "{{ talisker_branch | default('master') }}"
        force: true

    - name: Check if talisker.service unit file exists
      stat:
        path: /etc/systemd/system/talisker.service
      register: talisker_service_file

    - name: Stop talisker service if it exists
      become: true
      become_user: root
      systemd:
        name: talisker.service
        state: stopped
      when: talisker_service_file.stat.exists

    - name: Compile Talisker
      shell: |
        set -euo pipefail
        source $HOME/.cargo/env
        cd /home/ubuntu/talisker-src && \
        cargo build --release && \
        mkdir -p /home/ubuntu/talisker/bin && \
        cp target/release/talisker /home/ubuntu/talisker/bin
      args:
        executable: /bin/bash
        creates: /home/ubuntu/talisker/bin/talisker
      environment:
        RUSTC_WRAPPER: '/usr/local/bin/sccache'
        SCCACHE_BUCKET: 'snarkos-compiler-cache'
        SCCACHE_REGION: 'us-west-2'
        SCCACHE_S3_USE_SSL: 'true'
        SCCACHE_S3_KEY_PREFIX: 'talisker_linux_rust/'
        CARGO_INCREMENTAL: '0'
      async: 7200
      poll: 15

    - name: Ensure the talisker binary is executable
      file:
        path: "/home/ubuntu/talisker/bin/talisker"
        mode: '0755'

    - name: Deploy the talisker systemd service file
      become: true
      become_user: root
      template:
        src: talisker.service
        dest: /etc/systemd/system/talisker.service
        mode: '0644'

    - name: Reload systemd to read new talisker service file
      become: true
      become_user: root
      systemd:
        daemon_reload: true

    - name: Run aws config
      ansible.builtin.shell: |
        aws configure set default.region us-central-1
      environment:
        PYTHONNOUSERSITE: "1"   # ignore ~/.local site-packages

    - name: Setup aws config
      template:
        src: aws.config
        dest: /home/ubuntu/.aws/config
        mode: '0600'
      become: true

    - name: Get IP from inside the stress testing manager EC2 instance
      shell: curl -s http://checkip.amazonaws.com
      register: ip_result

    - name: Set fact for the stress testing manager IP
      set_fact:
        stress_testing_manager_ip: "{{ ip_result.stdout | trim }}"

    - name: Set up testing ansible vars
      template:
        src: ansible_vars.yml
        dest: /home/ubuntu/stress_testing/test_suites/single-region-tests/playbooks/vars.yml
        mode: '0600'
      become: true

    - name: Set up sync network testing ansible vars
      template:
        src: sync_network_test_ansible_vars.yml
        dest: /home/ubuntu/stress_testing/test_suites/network-sync-tests/playbooks/vars.talisker.yml
        mode: '0600'
      become: true

    - name: Set up the auto-run script
      template:
        src: auto_run_test_suite.sh
        dest: /home/ubuntu/stress_testing/test_suites/single-region-tests/auto_run_test_suite.sh
        mode: '0755'
      become: true

    - name: Set up the talisker control script
      template:
        src: talisker_control.sh
        dest: /home/ubuntu/talisker_control.sh
        mode: '0755'
      become: true

    - name: Restart talisker service
      become: true
      become_user: root
      systemd:
        name: talisker
        state: restarted
