---
- name: Set snarkOS binary path based on installation method
  set_fact:
    snarkos_bin_path: "/usr/bin"

- name: Preserve real snarkOS binary path (without flamegraph)
  set_fact:
    snarkos_real_bin: "/usr/bin/snarkos"

- name: Set optional flamegraph facts
  set_fact:
    snarkos_bin_path: "/root/.cargo/bin/flamegraph -o /tmp/snarkos_flamegraph.svg -- {{ snarkos_bin_path }}"
  when: create_flamegraph and node_id == flamegraph_node_id

- name: Deploy the snarkos systemd service file
  template:
    src: snarkos.service
    dest: /etc/systemd/system/snarkos.service
    mode: '0644'
  become: true

- name: Slurp the snarkos service file
  slurp:
    src: /etc/systemd/system/snarkos.service
  register: snarkos_service_file

- name: Reload systemd to read new snarkos service file
  systemd:
    daemon_reload: true
  become: true

- name: Restart snarkos service
  systemd:
    name: snarkos
    state: restarted
  become: true

- name: Prepare to print snarkos version and timestamp
  shell: |
    echo "Timestamp: $(date -Iseconds)"
    echo "SnarkOS Stress Tests commit_id: {{ snarkos_commit_id }}"
    echo "SnarkOS Branch: {{ snarkos_branch_name }}"
    echo "SnarkOS version:"
    {{ snarkos_real_bin }} -V
  register: snarkos_version_output
  args:
    executable: /bin/bash
  become: true

- name: SnarkOS version running is
  debug:
    var: snarkos_version_output.stdout_lines
