- name: Determine if snarkOS reinstall is needed
  import_playbook: ../../playbooks/maybe_reinstall_snarkos.yml

- name: Set bootstrap clients related facts
  hosts: localhost
  any_errors_fatal: true
  roles:
    - choose_bootstrap_client

- name: Reset validators
  hosts: snarkos_validator
  remote_user: ubuntu
  become: true
  strategy: free
  pre_tasks:
    - name: Set validators facts
      include_tasks: ../../playbooks/set_validator_facts.yml

    - name: Stop the honest validators
      systemd:
        name: snarkos
        state: stopped

    - name: Stop the malice validators
      systemd:
        name: snarkos-malice
        state: stopped
      ignore_errors: true # in case we never deployed malice

    - name: Remove existing ledger and node data directories on validators
      ansible.builtin.shell:
        cmd: |
          rm -rf /home/ubuntu/.ledger-* || true
          rm -rf /home/ubuntu/.node-data* || true

    - name: Remove existing log files
      ansible.builtin.shell:
        cmd: |
          rm /tmp/snarkos.log || true
          rm /home/ubuntu/consensus_timing_block_*.json || true
  roles:
    - snarkos_service
  tags: snarkos

- name: Reset clients
  hosts: snarkos_client
  remote_user: ubuntu
  become: true
  strategy: free
  pre_tasks:
    - name: Set clients facts
      include_tasks: ../../playbooks/set_client_facts.yml

    - name: Stop the clients
      systemd:
        name: snarkos
        state: stopped

    - name: Remove existing .ledger-* directories on clients
      ansible.builtin.shell:
        cmd: "rm -rf /home/ubuntu/.ledger-*"
  roles:
    - snarkos_service
  tags: snarkos_client
