input {
  file {
    path => "/tmp/tx-cannon.log"
    start_position => "beginning"
    codec => multiline {
      pattern => "^%{TIMESTAMP_ISO8601}"
      negate => true
      what => "previous"
    }
  }
}
filter {
  grok {
    match => { "message" => "^%{TIMESTAMP_ISO8601:timestamp}\s+%{LOGLEVEL:loglevel}\s+%{GREEDYDATA:message}" }
    overwrite => [ "message" ]
  }
  date {
    match => [ "timestamp", "ISO8601" ]
  }
  mutate {
    add_field => { "node_public_ip" => "{{ host_public_ip | default('unknown')  }}" }
    add_field => { "commit_hash" => "{{ commit_hash | default('unknown')  }}" }
    add_field => { "node_id" => "{{ node_id | default('unknown')  }}" }
  }
}
output {
  elasticsearch {
    index => "snarkos-logs-{{ devnet_name }}-%{+YYYY.MM.dd}"
    cloud_id => "{{ cloud_id }}"
    api_key => "{{ api_key }}"
  }
}