# Observability keys received from Infra team.
cloud_id: "your_elastic_cloud_id_here"
elastic_api_key: "your_elastic_api_key_here"
grafana_cloud_api_key: "your_grafana_cloud_api_key_here"

# Your own github access token.
github_token: "your_github_token_here" # link to generate: https://github.com/settings/tokens/new?scopes=repo&description=burn-in-testing-snarkos

# Observability infra vars
create_flamegraph: false
flamegraph_node_id: "0" # Validator node ID to generate flamegraph for

# Build vars
# NOTE: we just have a single build approach: if the binary does not exist on S3, use an ephemeral remote builder machine.
#       local build workflows are not advised due to environment/cross-compilation complexities.

snarkos_repo: "git@github.com:ProvableHQ/snarkOS-staging.git" # note the changed URL format
envs: "" # optional, e.g., "RUST_BACKTRACE=0 CARGO_PROFILE_RELEASE_DEBUG=false"
features: "" # optional, beware that "test_network" is not by defaultcompatible with production ledgers
snarkos_git_hash: "mainnet" # NOTE: can be a branch name or a commit hash
s3_bucket: release-bucket-2122415'

# Application vars
snarkos_verbosity: "6"
rest_rps: 1000000000

# Ansible vars
# ansible_python_interpreter: /usr/bin/python3.10


# Do not change the code below
release_name: "{{ snarkos_git_hash }}{{ '_' + features if (features is defined and features | length > 0) else '' }}"
