version: '3.8'

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command: 
      - '--path.rootfs=/host'
    volumes:
      - /proc:/host/proc
      - .:/config
    network_mode: host
    pid: host
    ports:
      - "9100:9100"
    privileged: true
    restart: unless-stopped
