# snarkos_clean.yml
- name: Clean snarkOS nodes
  hosts: "snarkos_node"
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Set node_id based on instance tag
      set_fact:
        node_id: "{{ tags['Dev'] }}"
      loop: "{{ groups['snarkos_node'] }}"
      run_once: true
      loop_control:
        loop_var: instance

    - name: Stop snarkos service
      systemd:
        name: snarkos
        state: stopped
      become: yes

    - name: Remove snarkos data
      ansible.builtin.shell:
        cmd: "/root/.cargo/bin/snarkos clean --dev {{ node_id }}"

    - name: Restart snarkos service
      systemd:
        name: snarkos
        state: started
        enabled: yes
      become: yes
