plugin: amazon.aws.aws_ec2

regions: us-west-1

keyed_groups:
  - key: tags.Role
    prefix: ""
    separator: ""
  - key: tags.Name
    prefix: ""
    separator: ""

filters:
  instance-state-name: running
  tag:Role: ["snarkos-node", "tx-cannon-bond-node", "tx-cannon-unbond-node", "prometheus-server"]
