---
- name: Fail if both snarkos_git_hash and snarkos_binary_tag are set
  fail:
    msg: "You cannot set both 'snarkos_git_hash' and 'snarkos_binary_tag'. Choose only one."
  when: snarkos_git_hash is defined and snarkos_git_hash | length > 0 and snarkos_binary_tag is defined and snarkos_binary_tag | length > 0

- name: Check if a local pre-built version should be used
  ansible.builtin.set_fact:
    use_local_pre_build: >-
      {{
        (snarkos_pre_build_location is defined and snarkos_pre_build_location | length > 0)
      }}

- name: Check if S3 pre-built version should be used
  ansible.builtin.set_fact:
    use_s3_pre_build: >-
      {{
        (snarkos_pre_build_location is undefined) and
        (s3_bucket is defined and s3_bucket | length > 0) and
        (use_snarkos_pre_build_s3 is defined and use_snarkos_pre_build_s3|bool)
      }}

- name: Check if local build should be used
  ansible.builtin.set_fact:
    use_local_build: >-
      {{
        (snarkos_pre_build_location is undefined) and
        (use_snarkos_pre_build_s3 is undefined or not use_snarkos_pre_build_s3|bool) and
        (snarkos_repo is defined and snarkos_repo | length > 0) and
        (snarkos_git_commit_local_build is defined and snarkos_git_commit_local_build | length > 0)
      }}

- name: Check if GitHub build should be used
  ansible.builtin.set_fact:
    use_github_build: >-
      {{
        (snarkos_pre_build_location is undefined) and
        (use_snarkos_pre_build_s3 is undefined or not use_snarkos_pre_build_s3|bool) and
        (snarkos_binary_tag is defined and snarkos_binary_tag | length > 0)
      }}

- name: Check if remote build should be used
  ansible.builtin.set_fact:
    use_remote_build: >-
      {{
        (snarkos_pre_build_location is undefined) and
        (use_snarkos_pre_build_s3 is undefined or not use_snarkos_pre_build_s3|bool) and
        (snarkos_git_hash is defined and snarkos_git_hash | length > 0) and
        (snarkos_repo is defined and snarkos_repo | length > 0)
      }}

- name: Check malice download method
  ansible.builtin.set_fact:
    use_malicious_snarkos_pre_build: >-
      {{
        (use_malicious_snarkos_pre_build is defined) and (use_malicious_snarkos_pre_build|bool)
      }}

- name: Ensure exactly one installation method is used
  ansible.builtin.fail:
    msg: "Exactly one installation method should be used."
  when: (use_local_build | int + use_github_build | int + use_remote_build | int | int + use_local_pre_build | int + use_s3_pre_build) != 1

- name: Ensure that if snarkos_git_commit_local_build_update is set, then the local build installation method is used
  fail:
    msg: "If snarkos_git_commit_local_build_update is set, then use the local build installation method."
  when: snarkos_git_commit_local_build_update is defined and snarkos_git_commit_local_build_update | length > 0 and not use_local_build

- name: Set git commit variable for standard build
  set_fact:
    snarkos_git_commit_to_build: "{{ snarkos_git_commit_local_build }}"
  when: snarkos_git_commit_local_build is defined

- name: Set standard release name
  set_fact:
    standard_release_name: "{{ generate_release_name | replace('COMMIT_HASH', snarkos_git_commit_to_build) | trim }}"
  when: snarkos_git_commit_local_build is defined

- name: Debug standard release name
  debug:
    msg: "Standard release name: '{{ standard_release_name }}'"
  when: snarkos_git_commit_local_build is defined

- name: Build and upload standard snarkOS to S3
  include_role:
    name: snarkos_build_locally
  when: hostvars['localhost'].use_local_build

- name: Set git commit variable for update build
  set_fact:
    snarkos_git_commit_to_build: "{{ snarkos_git_commit_local_build_update }}"
  when: snarkos_git_commit_local_build_update is defined and snarkos_git_commit_local_build_update | length > 0

- name: Set update release name
  set_fact:
    update_release_name: "{{ generate_release_name | replace('commit_hash', snarkos_git_commit_to_build) | trim }}"
  when: snarkos_git_commit_local_build_update is defined and snarkos_git_commit_local_build_update | length > 0

- name: Debug update release name
  debug:
    msg: "Update release name: '{{ update_release_name }}'"
  when: snarkos_git_commit_local_build_update is defined and snarkos_git_commit_local_build_update | length > 0

- name: Build and upload update snarkOS to S3
  include_role:
    name: snarkos_build_locally
  when: >
    hostvars['localhost'].use_local_build and 
    snarkos_git_commit_local_build_update is defined and 
    snarkos_git_commit_local_build_update | length > 0
