---
- name: Install dependencies
  hosts: all
  become: true
  gather_facts: true
  remote_user: ubuntu
  become_user: ubuntu
  tasks:
  - name: Set up basics and asdf
    block:
    - name: Install basic dependencies
      become: true
      become_user: root
      apt:
        update_cache: yes
        name:
          - awscli
          - curl
          - git
          - wget
          - vim
        state: latest

    - name: Install asdf
      become: true
      become_user: ubuntu
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "{{ ansible_user_dir }}/.asdf"
        depth: 1
        version: "{{ asdf | quote }}"
      register: result

    - name: asdf update
      become: true
      become_user: ubuntu
      shell: "bash -lc 'cd {{ ansible_user_dir }}/.asdf && git pull'"
      ignore_errors: yes
      when: result is failed

    - name: set env vars
      become: true
      become_user: ubuntu
      lineinfile:
        dest: "{{ shrc }}"
        state: present
        line: "{{ item.line }}"
      with_items:
      - line: ". $HOME/.asdf/completions/asdf.{{ sh }}"
        regexp: '^ \. \$HOME/\.asdf/completions/asdf\.{{ sh }}'
      - line: '. $HOME/.asdf/asdf.sh'
        regexp: '^ \. \$HOME/\.asdf/asdf\.sh'
    when: ansible_system == 'Linux' and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')
    vars:
      shrc: "{{ ansible_user_dir | quote }}/.{{ ansible_user_shell | basename | quote }}rc"
      sh: "{{ ansible_user_shell | basename | quote }}"
      asdf: "v0.14.1"

  - name: install prerequisite libraries for erlang 
    become: true
    become_user: root
    apt:
      update_cache: yes
      state: latest
      name:
      - build-essential
      - autoconf
      - m4
      - libwxgtk3.0-gtk3-dev
      - libncurses5-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng-dev
      - libssh-dev
      - unixodbc-dev
      - xsltproc
      - fop
      - libxml2-utils
      - libncurses-dev
      - openjdk-11-jdk
    when: ansible_system == 'Linux' and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')

  - name: Add Erlang asdf plugin
    become: true
    become_user: ubuntu
    block:
    - name: sh env
      ansible.builtin.shell:
      args:
        cmd: "{{ shenv_cmd }}"
        chdir: '{{ ansible_user_dir }}/'
      register: shenv
    - name: asdf plugin add erlang
      ansible.builtin.shell: |
        {{ source }} 
        asdf plugin add erlang
      args:
        executable: '{{ ansible_user_shell }}'
      register: result
      failed_when: result.rc != 0 and result.stderr | regex_search('(Plugin named .* already added)') == '' 
      vars:
        source: "{{ shenv.stdout_lines | map('regex_replace', '(^)', '. ') | join('\n') }}"
    vars:
      asdfsh: "{{ ansible_user_dir | quote }}/.asdf/asdf.sh"
      profile: "{{ ansible_user_dir | quote }}/.profile"
      shprofile: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename | regex_replace('$', '_') | regex_replace('zsh_', 'z') }}profile"
      shrc: "{{ ansible_user_dir | quote }}/.{{ ansible_user_shell | basename  | quote }}rc"
      shenv_cmd: "if [ -e {{ asdfsh }} ]; then echo '{{ asdfsh }}'; fi; if [ -e {{ shprofile }} ]; then echo '{{ shprofile }}'; fi; if [ -e {{ profile }} ]; then echo '{{ profile }}'; fi; if [ -e {{ shrc }} ]; then echo '{{ shrc }}'; fi"

  - name: Add Elixir asdf plugin
    become: true
    become_user: ubuntu
    block:
    - name: sh env
      ansible.builtin.shell:
      args:
        cmd: "{{ shenv_cmd }}"
        chdir: '{{ ansible_user_dir }}/'
      register: shenv
    - name: asdf plugin add elixir
      ansible.builtin.shell: |
        {{ source }} 
        asdf plugin add elixir
      args:
        executable: '{{ ansible_user_shell }}'
      register: result
      failed_when: result.rc != 0 and result.stderr | regex_search('(Plugin named .* already added)') == '' 
      vars: 
        source: "{{ shenv.stdout_lines | map('regex_replace', '(^)', '. ') | join('\n') }}"
    vars:
      asdfsh: "{{ ansible_user_dir | quote }}/.asdf/asdf.sh"
      profile: "{{ ansible_user_dir }}/.profile"
      shprofile: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename | regex_replace('$', '_') | regex_replace('zsh_', 'z') }}profile"
      shrc: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename }}rc"
      shenv_cmd: "if [ -e {{ asdfsh }} ]; then echo '{{ asdfsh }}'; fi; if [ -e {{ shprofile }} ]; then echo '{{ shprofile }}'; fi; if [ -e {{ profile }} ]; then echo '{{ profile }}'; fi; if [ -e {{ shrc }} ]; then echo '{{ shrc }}'; fi"

  - name: Add Rust asdf plugin
    become: true
    become_user: ubuntu
    block:
    - name: sh env
      ansible.builtin.shell:
      args:
        cmd: "{{ shenv_cmd }}"
        chdir: '{{ ansible_user_dir }}/'
      register: shenv
    - name: asdf plugin add rust
      ansible.builtin.shell: |
        {{ source }}
        asdf plugin add rust
      args:
        executable: '{{ ansible_user_shell }}'
      register: result
      failed_when: result.rc != 0 and result.stderr | regex_search('(Plugin named .* already added)') == '' 
      vars: 
        source: "{{ shenv.stdout_lines | map('regex_replace', '(^)', '. ') | join('\n') }}"
    vars:
      asdfsh: "{{ ansible_user_dir | quote }}/.asdf/asdf.sh"
      profile: "{{ ansible_user_dir }}/.profile"
      shprofile: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename | regex_replace('$', '_') | regex_replace('zsh_', 'z') }}profile"
      shrc: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename }}rc"
      shenv_cmd: "if [ -e {{ asdfsh }} ]; then echo '{{ asdfsh }}'; fi; if [ -e {{ shprofile }} ]; then echo '{{ shprofile }}'; fi; if [ -e {{ profile }} ]; then echo '{{ profile }}'; fi; if [ -e {{ shrc }} ]; then echo '{{ shrc }}'; fi"

  - name: Install Erlang
    become: true
    become_user: ubuntu
    block:
    - name: sh env
      ansible.builtin.shell:
      args:
        cmd: "{{ shenv_cmd }}"
        chdir: '{{ ansible_user_dir }}/'
      register: shenv
    - name: asdf install erlang
      ansible.builtin.shell: |
        {{ source }} 
        asdf install erlang {{ erlang | quote }}
      args:
        executable: '{{ ansible_user_shell }}'
      register: result
      when: ansible_system == 'Linux'
      vars: 
        source: "{{ shenv.stdout_lines | map('regex_replace', '(^)', '. ') | join('\n') }}"
    - name: show result
      debug:
        var: result
    - name: asdf global erlang
      ansible.builtin.shell: |
        {{ source }} 
        asdf global erlang {{ erlang | quote }}
      args:
        executable: '{{ ansible_user_shell }}'
      vars: 
        source: "{{ shenv.stdout_lines | map('regex_replace', '(^)', '. ') | join('\n') }}"
    vars:
      asdfsh: "{{ ansible_user_dir | quote }}/.asdf/asdf.sh"
      profile: "{{ ansible_user_dir }}/.profile"
      shprofile: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename | regex_replace('$', '_') | regex_replace('zsh_', 'z') }}profile"
      shrc: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename }}rc"
      shenv_cmd: "if [ -e {{ asdfsh }} ]; then echo '{{ asdfsh }}'; fi; if [ -e {{ shprofile }} ]; then echo '{{ shprofile }}'; fi; if [ -e {{ profile }} ]; then echo '{{ profile }}'; fi; if [ -e {{ shrc }} ]; then echo '{{ shrc }}'; fi"
      erlang: "latest"

  - name: Install Rust
    become: true
    become_user: ubuntu
    block:
    - name: sh env
      ansible.builtin.shell:
      args:
        cmd: "{{ shenv_cmd }}"
        chdir: '{{ ansible_user_dir }}/'
      register: shenv
    - name: asdf install rust
      ansible.builtin.shell: |
        {{ source }}
        asdf install rust {{ rust | quote }}
      args:
        executable: '{{ ansible_user_shell }}'
      register: result
      vars:
        source: "{{ shenv.stdout_lines | map('regex_replace', '(^)', '. ') | join('\n') }}"
    - name: show result
      debug:
        var: result
    - name: asdf global rust
      ansible.builtin.shell: |
        {{ source }}
        asdf global rust {{ rust | quote }}
      args:
        executable: '{{ ansible_user_shell }}'
      vars:
        source: "{{ shenv.stdout_lines | map('regex_replace', '(^)', '. ') | join('\n') }}"
    vars:
      asdfsh: "{{ ansible_user_dir | quote }}/.asdf/asdf.sh"
      profile: "{{ ansible_user_dir }}/.profile"
      shprofile: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename | regex_replace('$', '_') | regex_replace('zsh_', 'z') }}profile"
      shrc: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename }}rc"
      shenv_cmd: "if [ -e {{ asdfsh }} ]; then echo '{{ asdfsh }}'; fi; if [ -e {{ shprofile }} ]; then echo '{{ shprofile }}'; fi; if [ -e {{ profile }} ]; then echo '{{ profile }}'; fi; if [ -e {{ shrc }} ]; then echo '{{ shrc }}'; fi"
      rust: "latest"

  - name: Install ansible
    become: true
    become_user: root
    block:
    - name: Install dependencies for ansible
      apt:
        update_cache: yes
        name:
          - software-properties-common
        state: latest

    - name: Add Ansible repository into sources list
      ansible.builtin.apt_repository:
        repo: ppa:ansible/ansible
        state: present

    - name: Install Ansible
      apt:
        update_cache: yes
        name:
          - ansible
        state: latest

  - name: Install terraform
    become: true
    become_user: root
    unarchive:
      src: "https://releases.hashicorp.com/terraform/{{ vsn }}/terraform_{{ vsn }}_linux_amd64.zip"
      dest: /usr/bin
      remote_src: True
    vars:
      vsn: "1.10.2"
