---
- name: Clone or update snarkOS
  git:
    repo: "https://{{ github_token }}@github.com/{{ snarkos_repo | regex_replace('^https?://github\\.com/', '') }}"
    dest: "/home/ubuntu/snarkOS"
    version: "{{ snarkos_git_hash }}"
    clone: true
    update: true
    force: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Ubuntu dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - clang
      - gcc
      - libssl-dev
      - llvm
      - make
      - pkg-config
      - tmux
      - xz-utils
      - ufw
    state: present
  register: apt_result
  retries: 5
  delay: 60
  until: apt_result is success

- name: Install Rust programming language
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    executable: /bin/bash
    creates: "$HOME/.cargo/bin/rustup"

- name: Initialize envs_dict
  set_fact:
    envs_dict: {}

- name: Parse envs into a dictionary using dict filter
  set_fact:
    envs_dict: "{{ dict(envs | default('') | split(' ') | map('split', '=', 1)) }}"
  when: envs is defined and envs != ""

- name: Debug envs_dict
  debug:
    var: envs_dict
  when: envs is defined and envs != ""

- name: Set features flag
  set_fact:
    features_flag: >-
      {{
        "" if (features is not defined or features | length == 0)
        else "--features {{ features }}"
      }}

- name: Enable locktick build features in Cargo.tml
  shell: |
    tmp="$(mktemp)"
    sed 's/^# debug = "line-tables-only"/debug = "line-tables-only"/' Cargo.toml > "$tmp"
    mv "$tmp" Cargo.toml
    sed 's/^# strip = "none"/strip = "none"/' Cargo.toml > "$tmp"
    mv "$tmp" Cargo.toml
  args:
    executable: /bin/bash
    chdir: /home/ubuntu/snarkOS
  when: features is defined and 'locktick' in features

- name: Source cargo env and install snarkOS with git CLI
  ansible.builtin.shell:
    cmd: "source $HOME/.cargo/env && cargo install --locked --path . {{ features_flag }}"
  args:
    executable: /bin/bash
    chdir: /home/ubuntu/snarkOS
  environment: >-
    {{
      {
        'HOME': ansible_env.HOME,
        'CARGO_NET_GIT_FETCH_WITH_CLI': 'true'
      } | combine(envs_dict | default({}))
    }}
  become: true
