---
- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /home/ubuntu/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: '0664'
  become: true
  become_user: ubuntu

- name: Ensure Docker service is started
  service:
    name: docker
    state: started

- name: Create YAML scrape target file of all nodes
  ansible.builtin.template:
    src: prometheus.yml
    dest: /home/ubuntu/prometheus.yml
    mode: '0664'

- name: Run docker-compose up # noqa: no-changed-when
  command: docker-compose up -d --force-recreate
  args:
    chdir: /home/ubuntu/