---
- name: Add Elastic GPG key
  ansible.builtin.shell:
    cmd: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --batch --yes --dearmor -o /usr/share/keyrings/elastic-keyring.gpg"
  args:
    creates: /usr/share/keyrings/elastic-keyring.gpg

- name: Add Elastic APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    filename: elastic-8.x

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Filebeat
  ansible.builtin.apt:
    name: filebeat
    state: latest
  register: apt_result
  retries: 10
  delay: 30
  until: apt_result is success

- name: Copy Filebeat Configuration Template for snarkOS
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    mode: "0644"

- name: Restart Filebeat service
  systemd:
    name: filebeat
    state: restarted
  become: true
