global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    origin_prometheus: {{ devnet_name }}_devnet
scrape_configs:
  - job_name: 'snarkos'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
    - targets: [{% for host in groups['snarkos_node'] %}"{{ host }}:9000"
                 {%- if not loop.last %},{% endif %}
                 {%- endfor %}]
      labels:
        group: "snarkos"
  - job_name: 'Process_Exporter'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
    - targets: [{% for host in groups['snarkos_node'] %}"{{ host }}:9256"
                 {%- if not loop.last %},{% endif %}
                 {%- endfor %}]
      labels:
        group: "process_exporter"
