# Setting up and running tx-cannon on attacker-tx-cannon-node instances
- name: Set up and run tx-cannon
  hosts: "attacker_tx_cannon_node"
  become: yes
  remote_user: ubuntu
  vars:
    verbosity: "1"
  tasks:
    - name: Upload ../f_client_ips_and_ports.txt
      copy:
        src: ../f_client_ips_and_ports.txt
        dest: "/home/ubuntu/f_client_ips_and_ports.txt"
      become: yes

    - name: Install GitHub CLI
      shell: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
      args:
        executable: /bin/bash
      become: yes

    - name: Export tx-cannon GitHub token for gh CLI
      ansible.builtin.set_fact:
        gh_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"

    - name: Clone or update tx-cannon
      git:
        repo: "https://{{ gh_token }}:x-oauth-basic@github.com/AleoHQ/tx-cannon.git"
        dest: "/home/ubuntu/tx-cannon"
        version: "mainnet"

    - name: Gather facts from all nodes
      setup:

    - name: Download tx-cannon binary with GitHub CLI
      shell: >
        TAG=mainnet-latest

        apt-get install -y unzip

        GITHUB_TOKEN="{{ gh_token }}" gh release download ${TAG}
        --repo aleoHQ/tx-cannon
        --pattern "tx-cannon*unknown-linux-gnu.zip"
        --output "/usr/bin/tx-cannon.zip"
        --skip-existing

        unzip -o /usr/bin/tx-cannon.zip -d /usr/bin
      environment:
        GITHUB_TOKEN: "{{ gh_token }}"
      args:
        executable: /bin/bash
      become: yes

    - name: Make tx-cannon executable
      file:
        path: "/usr/bin/tx-cannon"
        mode: '0755'


    - name: Deploy 300k constraint programs in an infinite loop
      shell: |
        while true; do
          # Read a random line from f_client_ips_and_ports.txt
          RANDOM_LINE=$(shuf -n 1 /home/ubuntu/f_client_ips_and_ports.txt)
          
          # Go to the tx-cannon repository
          cd /home/ubuntu/tx-cannon &&
          sudo python3 tests/random_deployments/generate_random_programs.py tests/random_deployments/1M_constraints prog 10000 &&
          sudo /usr/bin/tx-cannon batch-deploy --manifest tests/random_deployments/1M_constraints/10000_prog.txt -k APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH -e "http://$RANDOM_LINE" --concurrent-deployments 1 >> tx-cannon-task1.log 2>&1
          
          # Note: Enclosed the URL in quotes in case $RANDOM_LINE contains special characters
        done
      args:
        executable: /bin/bash
      async: 360000  # This is a large number, ensuring the task is considered as running in the background
      poll: 0        # Ansible will not wait for the task to finish and move on immediately


    - name: Wait 10 minutes
      pause:
        minutes: 10

    - name: Set log folder name
      set_fact:
        log_folder: "./tx-cannon-logs/{{ inventory_hostname }}"

    - name: Create logs folder locally
      file:
        path: "{{ log_folder }}"
        state: directory

    - name: Fetch tx-cannon logs
      fetch:
        src: "/home/ubuntu/tx-cannon/tx-cannon-task1.log"
        dest: "{{ log_folder }}/tx-cannon.log"
        flat: yes
      ignore_errors: yes  # Optional, to proceed even if fetching logs fails