# snarkos_setup.yml
- name: Wait for SSH to become available
  hosts: "snarkos_node:snarkos_client_node"
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - name: Wait for SSH to become ready
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        timeout: 300
        delay: 10
        state: started


- name: Set up snarkOS nodes
  hosts: "snarkos_node:snarkos_client_node"
  become: yes
  remote_user: ubuntu
  vars:
    branch: "mainnet"
  tasks:
    - name: Gather facts from all nodes
      setup:

    - name: Set first node IP address
      set_fact:
        first_node_ip: "{{ hostvars[groups['snarkos_node'][0]]['public_ip_address']}}"
      when: groups['snarkos_node'] is defined and groups['snarkos_node'] | length > 0
      run_once: true

    - name: Determine the number of validator instances
      set_fact:
        num_instances: "{{ groups['snarkos_node'] | length }}"
      run_once: true

    - name: Set node_id based on instance tag
      set_fact:
        node_id: "{{ tags['Dev'] }}"

    - name: Install GitHub CLI
      shell: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
      args:
        executable: /bin/bash
      become: yes

    - name: Export GitHub token for gh CLI
      ansible.builtin.set_fact:
        gh_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"

    - name: Download snarkOS binary with GitHub CLI
      shell: >
        TAG=mainnet-staging-latest

        apt-get install -y unzip

        GITHUB_TOKEN="{{ gh_token }}" gh release download ${TAG}
        --repo ProvableHQ/snarkOS-staging
        --pattern "snarkos*unknown-linux-gnu.zip"
        --output "/usr/bin/snarkos.zip"
        --skip-existing

        unzip -o /usr/bin/snarkos.zip -d /usr/bin
      environment:
        GITHUB_TOKEN: "{{ gh_token }}"
      args:
        executable: /bin/bash
      become: yes

    - name: Slurp the commit hash
      ansible.builtin.slurp:
        src: '/usr/bin/SNARKOS_COMMIT_HASH'
      register: file_content_encoded

    - name: Decode the file commit from base64
      set_fact:
        commit_hash: "{{ file_content_encoded['content'] | b64decode | trim }}"

    - name: Make snarkos executable
      file:
        path: "/usr/bin/snarkos"
        mode: '0755'

    - name: Convert 'client_ips' string to list
      set_fact:
        client_ips_list: "{{ client_ips.split(' ') }}"

    - name: Split client IPs into chunks of 1
      set_fact:
        client_ips_chunks: "{{ client_ips_list | batch(1, []) }}"

    - name: Set environment variables for snarkos service
      set_fact:
        ansible_env:
          FIRST_NODE_IP: "{{ first_node_ip }}"
          VERBOSITY: 1
          NODE_ID: "{{ node_id }}"
          NUM_INSTANCES: "{{ num_instances }}"
      tags: always

    # Create a list of validator nodes only
    - name: Create list of snarkos_node hosts
      set_fact:
        snarkos_node_list: "{{ groups['snarkos_node'] }}"

    # Calculate index based on the validator list
    - name: Calculate index for current node within snarkos_node group
      set_fact:
        current_node_index: "{{ snarkos_node_list.index(inventory_hostname) }}"
      when: inventory_hostname in groups['snarkos_node']

    - name: Assign chunk of client IPs to current node
      set_fact:
        current_node_peers: "{{ client_ips_chunks[current_node_index|int % client_ips_chunks|length] }}"
      when: inventory_hostname in groups['snarkos_node']

    - name: Debug / Print Validator Node and Assigned Client IPs
      debug:
        msg: "Validator Node: {{ inventory_hostname }} - Assigned Client IPs: {{ current_node_peers }}"
      when: inventory_hostname in groups['snarkos_node'] and current_node_peers is defined

    - name: Deploy the snarkos systemd service file with dynamic peers
      template:
        src: snarkos.service
        dest: /etc/systemd/system/snarkos.service
      vars:
        peer_ips: "{{ current_node_peers }}"
      become: true
      when: inventory_hostname in groups['snarkos_node']

    - name: Reload systemd to read new snarkos service file
      systemd:
        daemon_reload: yes
      become: yes

    - name: Restart snarkos service on snarkos_node
      systemd:
        name: snarkos
        state: restarted
      become: yes
      when: "'snarkos_node' in group_names"

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: "'snarkos_node' in group_names"
        
    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
      when: "'snarkos_node' in group_names"

    - name: Run Docker Process Exporter for snarkos
      ansible.builtin.shell: >
        docker run -d --rm -p 9256:9256 --privileged -v /proc:/host/proc -v $(pwd):/config ncabatoff/process-exporter --procfs /host/proc -procnames snarkos
      args:
        executable: /bin/bash
      ignore_errors: yes # to make it idempotent
      when: "'snarkos_node' in group_names"

# logstash
- name: Install and Configure Logstash
  hosts: "snarkos_node"
  become: yes
  remote_user: ubuntu

  vars:
    cloud_id: "{{ lookup('env', 'ELASTIC_CLOUD_ID') }}"
    api_key: "{{ lookup('env', 'ELASTIC_API_KEY') }}"
    devnet_name: "{{ lookup('env', 'DEVNET_NAME') }}"

  tasks:
    - name: Set AWS Region Fact
      set_fact:
        aws_region: "{{ ansible_host.split('.')[1] }}"
      when: ansible_host is defined

    - name: Add Elastic GPG key
      ansible.builtin.shell:
        cmd: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --batch --yes --dearmor -o /usr/share/keyrings/elastic-keyring.gpg"

    - name: Add Elastic APT repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/elastic-8.x.list
        line: "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        create: yes
        state: present

    - name: Update and install Logstash
      ansible.builtin.apt:
        update_cache: yes
        name: logstash
        state: latest

    - name: Copy Logstash Configuration Template
      ansible.builtin.template:
        src: logstash.conf
        dest: /etc/logstash/conf.d/logstash.conf
      vars:
        host_public_ip: "{{ hostvars[inventory_hostname]['public_ip_address'] }}" 
        commit_hash: "{{ commit_hash }}"

    - name: Start Logstash Service
      ansible.builtin.systemd:
        name: logstash
        state: started
        enabled: yes

# metrics on grafana
- name: Install prometheus and enable remote forwarding to Grafana cloud
  hosts: prometheus_server
  become: yes 
  gather_facts: true 
  vars:
    ansible_user: ubuntu 
    grafana_cloud_api_key: "{{ lookup('env', 'GRAFANA_CLOUD_API_KEY') }}"
    devnet_name: "{{ lookup('env', 'DEVNET_NAME') }}"

  tasks:
    - name: Copy docker-compose.yml
      copy:
        src: docker-compose.yml  
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu 
        group: ubuntu  
      become_user: ubuntu

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: "/usr/local/bin/docker-compose"
        mode: 'u+x,g+x'

    - name: Create YAML scrape target file of all nodes
      ansible.builtin.template:
        src: prometheus.yml 
        dest: /home/ubuntu/prometheus.yml

    - name: Install unzip
      ansible.builtin.package:
        name: unzip
        state: present

    - name: Download, unzip, and set execute permissions on Grafana Agent
      ansible.builtin.shell: |
        curl -O -L "https://github.com/grafana/agent/releases/latest/download/grafana-agent-linux-amd64.zip" &&
        unzip "grafana-agent-linux-amd64.zip" &&
        chmod a+x grafana-agent-linux-amd64
      args:
        chdir: /home/ubuntu
        creates: grafana-agent-linux-amd64

    - name: Run docker-compose up
      command: docker-compose up -d --force-recreate
      args:
        chdir: /home/ubuntu/

# Deploy primary client nodes
- name: Deploy and restart snarkos-client service on client nodes
  hosts: snarkos_client_node
  become: yes
  remote_user: ubuntu
  tasks:

    - name: Determine the number of validator instances for client
      set_fact:
        num_instances: "{{ groups['snarkos_node'] | length }}"
      run_once: true

    # The node id starts from num_instances
    - name: Set node_id based on instance tag
      set_fact:
        node_id: "{{ (tags['Dev'] | int) + (num_instances | int) }}"
    
    - name: Set environment variables for snarkos service
      set_fact:
        ansible_env:
          VERBOSITY: 1
          NODE_ID: "{{ node_id }}"
          NUM_INSTANCES: "{{ num_instances }}"
      tags: always
    
    - name: Deploy the snarkos-client systemd service file
      template:
        src: snarkos-client.service
        dest: /etc/systemd/system/snarkos-client.service
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart snarkos-client service
      systemd:
        name: snarkos-client
        state: restarted