# Setting up and running tx-cannon on tx-cannon instances
- name: Set up and run tx-cannon
  hosts: "tx_cannon_node"
  become: yes
  remote_user: ubuntu
  tasks:
    - name: Clone or update tx-cannon
      git:
        repo: "https://{{ lookup('env', 'GITHUB_TOKEN') }}:x-oauth-basic@github.com/AleoHQ/tx-cannon.git"
        dest: "/home/ubuntu/tx-cannon"
        version: "kp/feat/build-ubuntu"

    - name: Make build_ubuntu.sh executable for tx-cannon
      file:
        path: "/home/ubuntu/tx-cannon/build_ubuntu.sh"
        mode: '0755'

    - name: Build tx-cannon using build_ubuntu.sh
      shell: cd /home/ubuntu/tx-cannon && sudo ./build_ubuntu.sh
      args:
        executable: /bin/bash

    - name: Run tx-cannon and capture logs
      shell: |
        cd /home/ubuntu/tx-cannon
        /root/.cargo/bin/tx-cannon deploy -p "tests/hello_world_flood/hello_hello.aleo" -k APrivateKey1zkp8CZNn3yeCseEtxuVPbDCwSyhGW6yZKUYKfgXmcpoGPWH -e http://{{ test_network_url }}:3033 >> tx-cannon.log 2>&1
      args:
        executable: /bin/bash
      async: 3600  # Adjust based on expected duration of the tx-cannon run
      poll: 0
      run_once: true
      delegate_to: "{{ groups['tx_cannon_node'][0] }}"

    - name: Wait for the deployed program to be ready
      uri:
        url: "http://{{ test_network_url }}:3033/testnet3/program/hello_hello.aleo"
        method: GET
        status_code: 200
        timeout: 10
      register: result
      until: result.status == 200
      retries: 30  # Number of retries
      delay: 10  # Delay in seconds between retries

    - name: Continue with tx-cannon batch-execute
      shell: |
        cd /home/ubuntu/tx-cannon
        /root/.cargo/bin/tx-cannon batch-execute --test "tests/hello_world_flood/hello_hello.toml" --threads 1 -e http://{{ test_network_url }}:3033 >> tx-cannon.log 2>&1
      args:
        executable: /bin/bash
      async: 3600  # Adjust based on expected duration of the tx-cannon run
      poll: 0

    - name: Fetch tx-cannon logs
      fetch:
        src: "/home/ubuntu/tx-cannon/tx-cannon.log"
        dest: "./{{ inventory_hostname }}-tx-cannon.log"
        flat: yes
      ignore_errors: yes  # Optional, to proceed even if fetching logs fails
