---
- name: Clone or update snarkOS
  git:
    repo: 'https://github.com/AleoHQ/snarkOS.git'
    dest: "/home/ubuntu/snarkOS"
    version: "mainnet-staging"
    clone: true
    update: true

- name: Make build-ubuntu.sh executable
  file:
    path: "/home/ubuntu/snarkOS/build_ubuntu.sh"
    mode: '0755'

- name: Build snarkOS using build_ubuntu.sh # noqa: no-changed-when
  shell: cd /home/ubuntu/snarkOS && sudo ./build_ubuntu.sh
  args:
    executable: /bin/bash

- name: Deploy the snarkos systemd service file
  template:
    src: snarkos.service
    dest: /etc/systemd/system/snarkos.service
    mode: '0644'
  become: true

- name: Slurp the snarkos service file
  slurp:
    src: /etc/systemd/system/snarkos.service
  register: snarkos_service_file

- name: Decode and print the snarkos service file contents
  debug:
    msg: "{{ snarkos_service_file['content'] | b64decode }}"

- name: Reload systemd to read new snarkos service file
  systemd:
    daemon_reload: true
  become: true

- name: Restart snarkos service
  systemd:
    name: snarkos
    state: restarted
  become: true
