- name: Set bootstrap clients related facts
  hosts: localhost
  any_errors_fatal: true
  roles:
    - choose_bootstrap_client

- name: Reset clients
  hosts: snarkos_client
  remote_user: ubuntu
  become: true
  strategy: free
  pre_tasks:
    - name: Set clients facts
      include_tasks: ../../playbooks/set_client_facts.yml

    - name: Stop the clients
      systemd:
        name: snarkos
        state: stopped

    - name: Remove existing ledger and node data directories on clients
      ansible.builtin.shell:
        cmd: |
          rm -rf /home/ubuntu/.ledger-* || true
          rm -rf /home/ubuntu/.node-data-* || true

  roles:
    - snarkos_service
  tags: snarkos_client
