name: Ansible Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install ansible-lint
        run: pip install ansible ansible-lint

      - name: Lint Ansible playbooks
        run: ./lint.sh

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: find test_suites -name "*.sh" -print0 | xargs -0 shellcheck -x --source-path=SCRIPTDIR
